# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesignTool
                                 A QGIS plugin
 This project involves the development of a specialized plugin for QGIS that automates the validation of a fiber optic network design against a critical set of predefined business and technical  rules. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        copyright            : (C) 2025 by Hamza Bouhali & Musa Haruna / M.design solutions
        email                : info@mdesignsolutions.be
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# Ensure bundled libraries (like python-docx) are available
plugin_dir = os.path.dirname(__file__)
libs_path = os.path.join(plugin_dir, "libs")
if libs_path not in sys.path:
    sys.path.append(libs_path)

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DesignTool class from file DesignTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .design_tool import DesignTool
    return DesignTool(iface)
