# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesignToolDialog
                                 A QGIS plugin
 This project involves the development of a specialized plugin for QGIS that automates the validation of a fiber optic network design against a critical set of predefined business and technical  rules. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hamza Bouhali & Musa Haruna / M.design solutions
        email                : info@mdesignsolutions.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis.PyQt import QtWidgets, uic  # type: ignore
from qgis.core import QgsMapLayerProxyModel # type: ignore
from qgis.PyQt.QtCore import (QFile, QTextStream, QTimer) # type: ignore
from qgis.gui import QgsFileWidget  # type: ignore

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'design_tool_dialog_base.ui'))

class DesignToolDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DesignToolDialog, self).__init__(parent)
        self.setupUi(self)

        self.is_processing = False  # Flag to indicate if processing is ongoing
        self.setup_progress_bar()

        # Connect checkbox to enable/disable point layer inputs
        if hasattr(self, 'updateAddressesCheckbox'):
            self.updateAddressesCheckbox.toggled.connect(self.togglePointLayerInput)

        # Connect checkbox to enable/disable intersection analysis inputs
        if hasattr(self, 'analyzeIntersectionsCheckbox'):
            self.analyzeIntersectionsCheckbox.toggled.connect(self.toggleIntersectionLayerInput)

        # Set filters for point layer combo box
        # if hasattr(self, 'pointLayerComboBox'):
        #     self.pointLayerComboBox.setFilters(QgsMapLayerProxyModel.PointLayer)

        # Set filter for surveyed addresses file widget
        if hasattr(self, 'surveyedAddressesFile'):
            self.surveyedAddressesFile.setFilter("Vector files (*.shp *.gpkg *.geojson *.kml)")

        # Initial state
        if hasattr(self, 'updateAddressesCheckbox'):
            self.togglePointLayerInput(self.updateAddressesCheckbox.isChecked())

        if hasattr(self, 'trenchesLayerComboBox'):
            self.trenchesLayerComboBox.setFilters(QgsMapLayerProxyModel.LineLayer)

        if hasattr(self, 'analyzeIntersectionsCheckbox'):
            self.toggleIntersectionLayerInput(self.analyzeIntersectionsCheckbox.isChecked())

        if hasattr(self, 'assignClustersByDistributionCheckbox'):
            self.assignClustersByDistributionCheckbox.toggled.connect(self.toggleClusterAssignmentInput)
        else:
            print("Warning: assignClustersByDistributionCheckbox not found in UI")

        # Apply custom style for the OK and Cancel buttons
        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)
        if ok_btn:
            ok_btn.setStyleSheet("""
                background-color: #1f3a52;
                color: #fff;
                padding: 6px 12px;
                border-radius: 8px;
                border: none;
                width: 60px;
                font-weight: bold;
                height: 15px;
            """)
            ok_btn.setText("Run")
        if cancel_btn:
            cancel_btn.setStyleSheet("""
                background-color: #e8eaed;
                color: #2e3440;
                padding: 6px 12px;
                border-radius: 8px;
                border: 1px solid #d0d7dc;
                width: 60px;
                font-weight: bold;
                height: 15px;
            """)
            cancel_btn.setText("Close")
        
        # ===== APPLY STYLE SHEET =====
        self.apply_stylesheet()

        # Connect the OK button to the design function
        self.button_box.accepted.connect(self.validate_inputs)
        self.button_box.rejected.connect(self.reject)

    def togglePointLayerInput(self, enabled):
        """Enable or disable the point layer input based on checkbox state."""
        if hasattr(self, 'pointLayerLabel'):
            self.pointLayerLabel.setEnabled(enabled)
        # if hasattr(self, 'pointLayerComboBox'):
        #     self.pointLayerComboBox.setEnabled(enabled)
        if hasattr(self, 'surveyedAddressesLabel'):
            self.surveyedAddressesLabel.setEnabled(enabled)
        if hasattr(self, 'surveyedAddressesFile'):
            self.surveyedAddressesFile.setEnabled(enabled)
    
    def toggleIntersectionLayerInput(self, enabled):
        """Enable or disable the intersection analysis input based on checkbox state."""
        if hasattr(self, 'trenchesLayerLabel'):
            self.trenchesLayerLabel.setEnabled(enabled)
        if hasattr(self, 'trenchesLayerComboBox'):
            self.trenchesLayerComboBox.setEnabled(enabled)
    
    # def get_point_layer(self):
    #     """Get the selected point layer"""
    #     if hasattr(self, 'pointLayerComboBox'):
    #         return self.pointLayerComboBox.currentLayer()
    #     return None

    def get_trenches_layer(self):
        """Get the selected trenches layer"""
        if hasattr(self, 'trenchesLayerComboBox'):
            return self.trenchesLayerComboBox.currentLayer()
        return None
        
    def get_surveyed_addresses_file_path(self):
        """Get the selected surveyed addresses file path"""
        if hasattr(self, 'surveyedAddressesFile'):
            return self.surveyedAddressesFile.filePath()
        return ''

    def setup_progress_bar(self):
        """Set up the progress bar"""
        if hasattr(self, 'progressBar'):
            self.progressBar.setValue(0)
            self.progressBar.setVisible(False)
            self.progressBar.setRange(0, 100)

            self.progressBar.setStyleSheet("""
            QProgressBar {
                border: 2px solid #2e3440;
                border-radius: 8px;
                background-color: #e8eaed;
                text-align: center;
                font-weight: bold;
                font-size: 14px;
                color: white;
                text-shadow: 
                    -2px -2px 0 #000,  
                    2px -2px 0 #000,
                    -2px 2px 0 #000,
                    2px 2px 0 #000,
                    -1px 0 0 #000,
                    1px 0 0 #000,
                    0 -1px 0 #000,
                    0 1px 0 #000;
            }
            
            QProgressBar::chunk {
                background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,
                    stop: 0 #1f3a52, stop: 1 #2e4d68);
                border-radius: 6px;
                margin: 1px;
            }
        """)

    def start_processing(self):
        """Start processing and show the progress bar"""
        self.is_processing = True
        if hasattr(self, 'progressBar'):
            self.progressBar.setVisible(True)
            self.progressBar.setValue(0)

        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)

        if ok_btn:
            ok_btn.setEnabled(False)
        if cancel_btn:
            cancel_btn.setText("Processing...")
            cancel_btn.setEnabled(False)

    def update_progress(self, value):
        """Update the progress bar value"""
        if hasattr(self, 'progressBar'):
            self.progressBar.setValue(value)
        QtWidgets.QApplication.processEvents()
    
    def finish_processing(self):
        """Finish processing and hide the progress bar"""
        self.is_processing = False
        if hasattr(self, 'progressBar'):
            self.progressBar.setValue(100)

        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)

        if ok_btn:
            ok_btn.setEnabled(True)
        if cancel_btn:
            cancel_btn.setText("Close")
            cancel_btn.setEnabled(True)

        if hasattr(self, 'progressBar'):
            QTimer.singleShot(1000, lambda: self.progressBar.setVisible(False))
        QTimer.singleShot(500, self.clear_inputs)

    def closeEvent(self, event):
        """Handle the close event"""
        if self.is_processing:
            QtWidgets.QMessageBox.warning(
                self,
                "Warning",
                "Processing is ongoing. Please wait until it finishes."
            )
        else:
            event.accept()

    def reject(self):
        """Override reject to prevent closing during processing"""
        if self.is_processing:
            QtWidgets.QMessageBox.warning(
                self,
                "Warning",
                "Processing is ongoing. Please wait until it finishes."
            )
            return
        super(DesignToolDialog, self).reject()

    def apply_stylesheet(self):
        # Path to your style.qss file (adjust path as needed)
        style_path = os.path.join(os.path.dirname(__file__), 'style.qss')

        if os.path.exists(style_path):
            style_file = QFile(style_path)
            if style_file.open(QFile.ReadOnly | QFile.Text):
                stream = QTextStream(style_file)
                style_sheet = stream.readAll()
                self.setStyleSheet(style_sheet)
                style_file.close()
            else:
                QtWidgets.QMessageBox.warning(self, "Warning", "Warning: Could not open style.qss")
        else:
            QtWidgets.QMessageBox.warning(self, "Warning", f"Warning: style.qss not found at {style_path}")

    def validate_inputs(self):
        """Validate inputs before accepting the dialog"""
        project_file_path = self.get_project_file_path()
        output_directory = self.get_output_directory()

        # Basic validation
        if not project_file_path:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select a design session project file.")
            return
            
        if not output_directory:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select an output directory.")
            return

        if hasattr(self, 'analyzeIntersectionsCheckbox') and self.analyzeIntersectionsCheckbox.isChecked():
            trenches_layer = self.get_trenches_layer()
            if not trenches_layer:
                QtWidgets.QMessageBox.warning(self, "Warning", "Please select a trenches layer when 'Analyze sidewalk intersections' is checked.")
                return

        # Validate surveyed addresses file if checkbox is checked
        if hasattr(self, 'updateAddressesCheckbox') and self.updateAddressesCheckbox.isChecked():
            surveyed_addresses_file = self.get_surveyed_addresses_file_path()
            if not surveyed_addresses_file:
                QtWidgets.QMessageBox.warning(self, "Warning", "Please select a surveyed addresses file when 'Update Addresses' is checked.")
                return
        
        self.accept()

    def get_zip_file_path(self):
        """Get the selected zip file path"""
        if hasattr(self, 'designSessionZipFile'):
            return self.designSessionZipFile.filePath()
        return ''
    
    def get_project_file_path(self):
        """Get the selected project file path"""
        if hasattr(self, 'designSessionProjectFile'):
            return self.designSessionProjectFile.filePath()
        return ''
    
    def get_output_directory(self):
        """Get the selected output directory"""
        if hasattr(self, 'OutputDirectoryOfGeneratedReports'):
            return self.OutputDirectoryOfGeneratedReports.filePath()
        return ''
    
    def get_analyze_intersections(self):
        """Check if analyze intersections checkbox is checked"""
        if hasattr(self, 'analyzeIntersectionsCheckbox'):
            return self.analyzeIntersectionsCheckbox.isChecked()
        return False
    
    def clear_inputs(self):
        """Clear all input fields and checkboxes"""
        # Clear file paths
        if hasattr(self, 'designSessionProjectFile'):
            self.designSessionProjectFile.setFilePath('')
        
        if hasattr(self, 'designSessionZipFile'):
            self.designSessionZipFile.setFilePath('')
        
        if hasattr(self, 'OutputDirectoryOfGeneratedReports'):
            self.OutputDirectoryOfGeneratedReports.setFilePath('')
        
        if hasattr(self, 'surveyedAddressesFile'):
            self.surveyedAddressesFile.setFilePath('')

    def toggleClusterAssignmentInput(self, enabled):
        """Enable or disable cluster assignment inputs based on checkbox state."""
        # No additional inputs needed for this feature - it uses project layers
        print(f"Cluster assignment checkbox: {enabled}")

    def get_assign_clusters_by_distribution(self):
        """Check if assign clusters by distribution checkbox is checked"""
        if hasattr(self, 'assignClustersByDistributionCheckbox'):
            state = self.assignClustersByDistributionCheckbox.isChecked()
            print(f"get_assign_clusters_by_distribution() returning: {state}")
            return state
        print("Warning: assignClustersByDistributionCheckbox not found")
        return False


    def validate_inputs_only(self):
        """Validate inputs without closing dialog - returns True if valid"""
        project_file_path = self.get_project_file_path()
        output_directory = self.get_output_directory()

        if not project_file_path:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select a design session project file.")
            return False
            
        if not output_directory:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select an output directory.")
            return False

        if hasattr(self, 'analyzeIntersectionsCheckbox') and self.analyzeIntersectionsCheckbox.isChecked():
            trenches_layer = self.get_trenches_layer()
            if not trenches_layer:
                QtWidgets.QMessageBox.warning(self, "Warning", "Please select a trenches layer when 'Analyze sidewalk intersections' is checked.")
                return False

        if hasattr(self, 'updateAddressesCheckbox') and self.updateAddressesCheckbox.isChecked():
            surveyed_addresses_file = self.get_surveyed_addresses_file_path()
            if not surveyed_addresses_file:
                QtWidgets.QMessageBox.warning(self, "Warning", "Please select a surveyed addresses file when 'Update Addresses' is checked.")
                return False

        return True