# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyApp
                                 A QGIS plugin
 M.design Survey 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by MUSA/HAMZA
        email                : info@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
import shutil
import traceback

from qgis.core import (Qgis, QgsCoordinateReferenceSystem,  # type: ignore
                       QgsCoordinateTransform, QgsCoordinateTransformContext,
                       QgsDefaultValue, QgsEditorWidgetSetup, QgsFeature,
                       QgsField, QgsFieldConstraints, QgsFillSymbol,
                       QgsGeometry, QgsLinePatternFillSymbolLayer,
                       QgsLineSymbol, QgsMapLayer, QgsMarkerSymbol,
                       QgsProcessingContext, QgsProcessingFeedback, QgsProject,
                       QgsRasterLayer, QgsRuleBasedRenderer,
                       QgsSimpleFillSymbolLayer, QgsSingleSymbolRenderer,
                       QgsVectorFileWriter, QgsVectorLayer, QgsWkbTypes)
from qgis.PyQt.QtCore import (QCoreApplication, QSettings,  # type: ignore
                              QTranslator, QVariant)
from qgis.PyQt.QtGui import QColor  # type: ignore
from qgis.PyQt.QtGui import QIcon  # type: ignore
from qgis.PyQt.QtWidgets import QAction  # type: ignore

from .plugin_logger import PluginLogger
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .survey_app_dialog import SurveyAppDialog
from .utils.demand_utils import check_and_split_demand_points, add_missing_addresses_from_gov


class SurveyApp:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SurveyApp_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&M.design Survey ')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Initialize logger
        SUPABASE_URL = "https://mjqzyvlkxjvemmkostrv.supabase.co"
        SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcXp5dmxreGp2ZW1ta29zdHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMDE5OTIsImV4cCI6MjA3ODY3Nzk5Mn0.xfuztVHXgDIxuueFi4zDt4sVdw4pJ8VJsRc3bA_SJ50"
        self.logger = PluginLogger(SUPABASE_URL, SUPABASE_KEY)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SurveyApp', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Survey'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def get_actions(self):
        return self.actions

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&M.design Survey '),
                action)

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            self.dlg = SurveyAppDialog(iface=self.iface)  # Pass iface to dialog

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        # See if OK was pressed
        if result:
            current_tab = self.dlg.tabWidget.currentIndex()
            
            if current_tab == 0:
                # Survey Creation tab - run normal survey creation
                self.process_survey_setup()
            elif current_tab == 1:
                # Survey Validation tab - check if validation should run
                if self.dlg.homecountValidationCheckbox.isChecked():
                    # The validation was already run by the dialog's custom_accept method
                    # You can add any post-validation logic here if needed
                    self.iface.messageBar().pushMessage(
                        "Success",
                        "Validation completed successfully!",
                        level=Qgis.Success,
                        duration=10
                    )
                else:
                    # User clicked OK but no validation was selected
                    self.iface.messageBar().pushMessage(
                        "Info",
                        "No validation options were selected.",
                        level=Qgis.Info,
                        duration=5
                    )

    def process_survey_setup(self):
        """Gets data from the dialog and creates multiple project structures - one for each polygon feature."""
        project_name = self.dlg.get_project_name()
        output_dir = self.dlg.get_output_directory()
        polygon_layer = self.dlg.get_selected_polygon_layer()
        buildings_layer = self.dlg.get_selected_buildings_layer()
        address_layer = self.dlg.get_selected_address_layer()
        crossing_layer = self.dlg.get_selected_crossing_layer()
        facade_layer = self.dlg.get_selected_facade_layer()
        sidewalk_layer = self.dlg.get_selected_sidewalk_layer()
        pole_layer = self.dlg.get_selected_pole_layer()
        aerial_layer = self.dlg.get_selected_aerial_layer()

        # Always use EPSG:31370 as the project CRS
        project_crs = QgsCoordinateReferenceSystem('EPSG:31370')
        print(f"Using fixed project CRS: {project_crs.authid()}")

        # 1. Validate inputs
        if not all([project_name, output_dir, polygon_layer]):
            self.iface.messageBar().pushMessage(
                "Error", "Project Name, Output Directory, and a Polygon Layer must be specified.", level=Qgis.Critical
            )
            return

        # Get polygon features count
        polygon_count = polygon_layer.featureCount() # type: ignore
        print(f"Found {polygon_count} polygon features")

        if polygon_count == 0:
            self.iface.messageBar().pushMessage(
                "Error", "Polygon layer has no features.", level=Qgis.Critical
            )
            return

        # Save current project extent and layers
        current_project = QgsProject.instance()
        
        try:
            # Process each polygon feature separately
            created_projects = 0
            for i, polygon_feature in enumerate(polygon_layer.getFeatures()): # type: ignore
                print(f"\n{'='*60}")
                print(f"Processing polygon {i+1} of {polygon_count}")
                print(f"{'='*60}")
                
                # Create a memory layer with just this polygon feature
                single_polygon_layer = QgsVectorLayer("Polygon?crs=EPSG:31370", f"temp_polygon_{i}", "memory")
                dp = single_polygon_layer.dataProvider()
                
                # Add the polygon feature
                geom = polygon_feature.geometry()
                # Reproject geometry to EPSG:31370 if needed
                if polygon_layer.crs().authid() != 'EPSG:31370': # type: ignore
                    transform = QgsCoordinateTransform(polygon_layer.crs(), project_crs, QgsProject.instance()) # type: ignore
                    geom.transform(transform)
                
                new_feature = QgsFeature()
                new_feature.setGeometry(geom)
                dp.addFeatures([new_feature])
                single_polygon_layer.updateExtents()
                
                # Create project name with suffix (PT1, PT2, etc.)
                suffix = f"_PT{i+1}"
                current_project_name = f"{project_name}{suffix}"
                
                # Call the function to create a single project for this polygon
                success = self.create_single_project(
                    current_project_name, output_dir, single_polygon_layer,
                    buildings_layer, address_layer, crossing_layer, facade_layer,
                    sidewalk_layer, pole_layer, aerial_layer, project_crs, i+1
                )
                
                if success:
                    created_projects += 1
                    print(f"Successfully created project: {current_project_name}")
                else:
                    print(f"Failed to create project for polygon {i+1}")
            
            # Show summary message
            if created_projects > 0:
                self.iface.messageBar().pushMessage(
                    "Success",
                    f"Created {created_projects} QField-ready projects in '{output_dir}'",
                    level=Qgis.Success,
                    duration=15
                )
            else:
                self.iface.messageBar().pushMessage(
                    "Warning",
                    "No projects were created successfully.",
                    level=Qgis.Warning,
                    duration=10
                )
            
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "Error", f"An error occurred: {e}", level=Qgis.Critical
            )
            import traceback
            print(f"Full error traceback: {traceback.format_exc()}")

    def create_single_project(self, project_name, output_dir, polygon_layer,
                            buildings_layer, address_layer, crossing_layer,
                            facade_layer, sidewalk_layer, pole_layer,
                            aerial_layer, project_crs, polygon_index):
        """Create a single project for a specific polygon feature."""
        
        import traceback  # Import traceback at function level
        
        # 1. Define paths
        template_dir = os.path.join(self.plugin_dir, 'template')
        new_project_dir = os.path.join(output_dir, project_name)

        # Check if template exists
        if not os.path.exists(template_dir):
            print(f"Template directory not found at: {template_dir}")
            return False

        try:
            # 2. Create new folder
            if os.path.exists(new_project_dir):
                print(f"Project directory '{new_project_dir}' already exists. Overwriting content.")
                shutil.rmtree(new_project_dir)

            os.makedirs(new_project_dir)

            # 3. Process demand points based on selected options
            selected_checks = self.dlg.get_selected_checks()
            
            split_demand_enabled = selected_checks.get('split_demandpoints', False)
            add_missing_addresses_enabled = selected_checks.get('add_missing_addresses', False)
            
            print(f"\n=== Processing Demand Points ===")
            print(f"Split demand points: {split_demand_enabled}")
            print(f"Add missing addresses: {add_missing_addresses_enabled}")
            
            # Store the final address layer to use
            address_layer_for_project = address_layer
            
            # Process according to selected options
            if split_demand_enabled and add_missing_addresses_enabled:
                print("\nStep 1: Running check_and_split_demand_points...")
                try:
                    split_demand_layer = check_and_split_demand_points(self.iface)
                    if split_demand_layer:
                        print(f"Step 1 completed: {split_demand_layer.featureCount()} features in demand layer")
                    else:
                        print("Step 1 failed. Using default address layer.")
                        split_demand_layer = None
                except Exception as e:
                    print(f"Error in step 1: {e}")
                    print(traceback.format_exc())
                    split_demand_layer = None
                
                if split_demand_layer:
                    print("\nStep 2: Running add_missing_addresses_from_gov on result...")
                    try:
                        # Temporarily add the layer to the project
                        QgsProject.instance().addMapLayer(split_demand_layer, False)
                        
                        final_demand_layer = add_missing_addresses_from_gov(self.iface)
                        
                        QgsProject.instance().removeMapLayer(split_demand_layer)
                        
                        if final_demand_layer:
                            print(f"Step 2 completed: {final_demand_layer.featureCount()} features in demand layer")
                            address_layer_for_project = final_demand_layer
                            print("Using final result as address layer for project")
                        else:
                            print("Step 2 failed. Using result from step 1.")
                            address_layer_for_project = split_demand_layer
                    except Exception as e:
                        print(f"Error in step 2: {e}")
                        print(traceback.format_exc())
                        address_layer_for_project = split_demand_layer
                else:
                    print("\nBoth options selected but step 1 failed. Using default address layer.")
            
            elif split_demand_enabled:
                print("\nRunning check_and_split_demand_points...")
                try:
                    edited_demand_layer = check_and_split_demand_points(self.iface)
                    if edited_demand_layer:
                        print(f"Split demand points completed: {edited_demand_layer.featureCount()} features")
                        address_layer_for_project = edited_demand_layer
                        print("Using edited demand layer as address layer for project")
                    else:
                        print("Split demand points operation did not complete successfully. Using default address layer.")
                except Exception as e:
                    print(f"Error running split demand points: {e}")
                    print("Using default address layer instead.")
                    print(traceback.format_exc())
            
            elif add_missing_addresses_enabled:
                print("\nRunning add_missing_addresses_from_gov...")
                try:
                    edited_demand_layer = add_missing_addresses_from_gov(self.iface)
                    if edited_demand_layer:
                        print(f"Add missing addresses completed: {edited_demand_layer.featureCount()} features")
                        address_layer_for_project = edited_demand_layer
                        print("Using edited demand layer as address layer for project")
                    else:
                        print("Add missing addresses operation did not complete successfully. Using default address layer.")
                except Exception as e:
                    print(f"Error running add missing addresses: {e}")
                    print("Using default address layer instead.")
                    print(traceback.format_exc())
            
            else:
                print("\n=== Using default address/demand point layer (no options selected) ===")

            # 4. Define layers to copy with their photo field configurations
            layers_to_copy = {
                'polygon': {
                    'layer': polygon_layer,
                    'photo_fields': [],
                    'layer_attributes': [],
                    'display_name': 'Survey Area',
                    'clip': False,
                    'layer_type': 'polygon'
                },
                'buildings': {
                    'layer': buildings_layer,
                    'photo_fields': [],
                    'layer_attributes': ['BLDG_ID', 'STREETNAME', 'INCLUDE'],
                    'display_name': 'Buildings',
                    'clip': True,
                    'layer_type': 'buildings'
                },
                'address': {
                    'layer': address_layer_for_project,
                    'photo_fields': ['photo', 'mdu'],
                    'layer_attributes': ['P2P_HOMES', 'INCLUDE', 'CITY', 'STREETNAME', 'ADDRESS_SU', 'BOX', 'LAT', 'LON', 'POSTCODE', 'TINA_UUID', 'DEMAND', 'EXC_REASON', 'GISTOOL_ID', 'ADDRESS_NU'],
                    'display_name': 'Address Points',
                    'clip': True,
                    'layer_type': 'address'
                },
                'crossing': {
                    'layer': crossing_layer,
                    'photo_fields': ['photostart', 'photoend'],
                    'layer_attributes': ['SUBTYPE'],
                    'display_name': 'Crossings',
                    'clip': True,
                    'layer_type': 'crossing'
                },
                'facade': {
                    'layer': facade_layer,
                    'photo_fields': [],
                    'layer_attributes': ['SPAN', 'TRANSITION'],
                    'display_name': 'Facades',
                    'clip': True,
                    'layer_type': 'facade'
                },
                'sidewalk': {
                    'layer': sidewalk_layer,
                    'photo_fields': ['photostart', 'photoend'],
                    'layer_attributes': ['SUBTYPE', 'STREETNAME', 'SUBTYPE2'],
                    'display_name': 'Sidewalks',
                    'clip': True,
                    'layer_type': 'sidewalk'
                },
                'pole': {
                    'layer': pole_layer,
                    'photo_fields': ['photo'],
                    'layer_attributes': ['GISTOOL_ID', 'IDENTIFIER', 'INCLUDE', 'EXISTING', 'LOCKED', 'EQUIPMENT'],
                    'display_name': 'Poles',
                    'clip': True,
                    'layer_type': 'pole'
                },
                'aerial': {
                    'layer': aerial_layer,
                    'photo_fields': ['photo'],
                    'layer_attributes': ['LOCKED', 'INCLUDE', 'AVOID'],
                    'display_name': 'Aerial Drop connections',
                    'clip': True,
                    'layer_type': 'aerial'
                }
            }

            # 5. Process and save each layer to shapefile FIRST
            shapefile_paths = []
            layers_created = {}

            for layer_type, layer_info in layers_to_copy.items():
                layer = layer_info['layer']
                photo_fields = layer_info['photo_fields']
                layer_attributes = layer_info['layer_attributes']
                display_name = layer_info['display_name']
                should_clip = layer_info['clip']

                if layer is not None:
                    # Create safe filename
                    safe_name = "".join(c if c.isalnum() or c in "._-" else "_" for c in display_name)
                    shapefile_output_path = os.path.join(new_project_dir, f"{safe_name}.shp")

                    # Create a temporary layer with the new fields (and clip if needed)
                    temp_layer = self.copy_layer_with_specific_fields(
                        layer, layer_attributes, photo_fields, project_crs, 
                        polygon_layer if should_clip else None, layer_type
                    )

                    if temp_layer:
                        # Save the temporary layer to shapefile with explicit CRS
                        options = QgsVectorFileWriter.SaveVectorOptions()
                        options.driverName = "ESRI Shapefile"
                        options.fileEncoding = "utf-8"
                        options.overrideGeometryType = QgsWkbTypes.Unknown
                        options.includeZ = False
                        options.includeM = False
                        
                        # Force the CRS to EPSG:31370
                        options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
                        options.layerOptions = ['ENCODING=UTF-8']
                        
                        transform_context = QgsCoordinateTransformContext()
                        error = QgsVectorFileWriter.writeAsVectorFormatV2(
                            temp_layer,
                            shapefile_output_path,
                            transform_context,
                            options
                        )

                        if error[0] != QgsVectorFileWriter.NoError:
                            print(f"Failed to save {layer_type} layer: {error[1]}")
                        else:
                            print(f"Successfully saved {layer_type} layer to: {shapefile_output_path}")
                            # Store layer info for later addition to project
                            layers_created[layer_type] = {
                                'path': shapefile_output_path,
                                'name': display_name,
                                'type': layer_type,
                                'temp_layer': temp_layer
                            }
                            shapefile_paths.append({
                                'path': shapefile_output_path,
                                'name': display_name,
                                'type': layer_type
                            })
                    else:
                        print(f"Failed to create temporary layer for {layer_type}")
                else:
                    print(f"Skipping {layer_type} layer (not provided)")

            # 6. Create a new QgsProject instance
            new_project = QgsProject()
            
            # Force EPSG:31370 as project CRS
            new_project.setCrs(QgsCoordinateReferenceSystem('EPSG:31370'))
            print(f"Project CRS set to: {new_project.crs().authid()}")

            # 7. Add GRB Grayscale Basemap (WMS) first
            grb_url = (
                "contextualWMSLegend=0&dpiMode=7"
                "&url=https://geo.api.vlaanderen.be/GRB-basiskaart-grijs/wms"
                "&layers=GRB_BSK_GRIJS"
                "&styles="
                "&format=image/png"
                "&crs=EPSG:31370"
            )
            grb_layer = QgsRasterLayer(grb_url, "GRB Basemap", "wms")

            if grb_layer.isValid():
                grb_layer.setCrs(QgsCoordinateReferenceSystem('EPSG:31370'))
                new_project.addMapLayer(grb_layer, False)
                print("GRB basemap added successfully")
            else:
                print(f"GRB basemap failed: {grb_layer.error().message()}")

            # 8. Load and add each saved shapefile to the project
            map_layers = []
            polygon_extent = None
            
            # First, add the polygon layer to get its extent
            if 'polygon' in layers_created:
                layer_info = layers_created['polygon']
                shapefile_path = layer_info['path']
                layer_name = layer_info['name']
                layer_type = layer_info['type']
                
                if os.path.exists(shapefile_path):
                    vlayer = QgsVectorLayer(shapefile_path, layer_name, "ogr")
                    
                    if vlayer.isValid():
                        # Force CRS to EPSG:31370
                        vlayer.setCrs(QgsCoordinateReferenceSystem('EPSG:31370'))
                        print(f"Loaded polygon layer with CRS: {vlayer.crs().authid()}")
                        
                        # Apply styling
                        self.apply_red_outline_style(vlayer)
                        
                        # Get polygon extent for setting project extent
                        polygon_extent = vlayer.extent()
                        
                        # Add to map layers list
                        map_layers.append(vlayer)
                        
                        # Apply any other configurations
                        self.add_comment_field(vlayer)
                        vlayer.setReadOnly(False)
                    else:
                        print(f"Failed to load polygon layer: {vlayer.error().message()}")

            # Then add all other layers
            for layer_type in ['buildings', 'address', 'crossing', 'facade', 'sidewalk', 'pole', 'aerial']:
                if layer_type in layers_created:
                    layer_info = layers_created[layer_type]
                    shapefile_path = layer_info['path']
                    layer_name = layer_info['name']
                    
                    if os.path.exists(shapefile_path):
                        vlayer = QgsVectorLayer(shapefile_path, layer_name, "ogr")
                        
                        if vlayer.isValid():
                            # Force CRS to EPSG:31370
                            vlayer.setCrs(QgsCoordinateReferenceSystem('EPSG:31370'))
                            print(f"Loaded {layer_type} layer with CRS: {vlayer.crs().authid()}")
                            
                            # Apply appropriate styling
                            if layer_type == 'buildings':
                                self.apply_striped_symbology(vlayer)
                            else:
                                self.apply_surveyed_symbology(vlayer)
                            
                            # Configure fields
                            if layer_type != 'polygon':
                                self.configure_surveyed_field(vlayer)
                            
                            if layer_type in ['address', 'crossing', 'facade', 'sidewalk', 'pole', 'aerial']:
                                self.configure_photo_fields(vlayer)
                            
                            if layer_type != 'polygon':
                                self.configure_required_fields(vlayer, layer_type)
                            
                            # Add comment field
                            self.add_comment_field(vlayer)
                            
                            # Setup auto XY for address layer
                            if layer_type == 'address':
                                self.setup_auto_xy_from_project_crs(vlayer, project_crs)
                            
                            vlayer.setReadOnly(False)
                            map_layers.append(vlayer)
                        else:
                            print(f"Failed to load {layer_type} layer: {vlayer.error().message()}")
            
            # 9. Add all layers to the project
            for vlayer in map_layers:
                new_project.addMapLayer(vlayer)
                print(f"Added layer to project: {vlayer.name()}")

            # 10. Set project title and metadata
            new_project.setTitle(project_name)
            
            # Set project extent based on polygon layer
            if polygon_extent:
                from qgis.core import QgsReferencedRectangle # type: ignore
                # Set the project's home extent without using QgsMapCanvas
                # Create a small buffer around the polygon for better visibility
                buffered_extent = polygon_extent.buffered(polygon_extent.width() * 0.1)
                # Create a QgsReferencedRectangle with the project CRS
                referenced_extent = QgsReferencedRectangle(buffered_extent, QgsCoordinateReferenceSystem('EPSG:31370'))
                # Set the project's home extent
                new_project.viewSettings().setDefaultViewExtent(referenced_extent)
                print(f"Set project extent to: {buffered_extent.toString()}")
            
            # 11. Save the project file
            project_file = os.path.join(new_project_dir, f"{project_name}.qgz")
            
            # Ensure the project uses EPSG:31370
            new_project.setCrs(QgsCoordinateReferenceSystem('EPSG:31370'))
            
            success = new_project.write(project_file)

            if success:
                print(f"\nProject '{project_name}' created successfully!")
                print(f"Location: {project_file}")
                print(f"CRS: {new_project.crs().authid()}")
                print(f"Layers: {len(map_layers)}")
                
                # LOG THE SURVEY CREATION
                self.logger.log(
                    types="survey",
                    design_session=project_name,
                    description=f"Created survey project with {len(map_layers)} layers (Polygon {polygon_index})"
                )
                
                # Test opening the project
                test_project = QgsProject()
                if test_project.read(project_file):
                    print(f"Project can be opened successfully")
                    print(f"Test project CRS: {test_project.crs().authid()}")
                    test_project.clear()
                else:
                    print(f"Warning: Project file may have issues")
                
                return True
            else:
                print(f"Failed to save project file: {new_project.error()}")
                return False

        except Exception as e:
            print(f"Error creating project {project_name}: {e}")
            print(f"Full error traceback: {traceback.format_exc()}")
            return False

    def copy_layer_with_specific_fields(self, original_layer, layer_attributes, photo_fields, target_crs, clip_layer=None, layer_type=None):
        """Copy a layer with ALL original fields, plus UUID and SURVEYED field.
        All layers are transformed to the target_crs (EPSG:31370).
        If clip_layer is provided, the features will be clipped to that layer's geometry."""
        
        if not original_layer or not original_layer.isValid():
            return None

        temp_layer = None
        try:
            # Always use EPSG:31370 as target CRS
            target_crs = QgsCoordinateReferenceSystem('EPSG:31370')
            
            # Check if this layer should be empty
            should_be_empty = layer_type in ['facade', 'pole', 'aerial', 'crossing']

            if should_be_empty:
                print(f"Creating empty layer for {layer_type}")
                # Create an empty memory layer
                temp_layer = QgsVectorLayer(
                    f"{QgsWkbTypes.displayString(original_layer.wkbType())}?crs=EPSG:31370", 
                    f"temp_{original_layer.name()}", 
                    "memory"
                )

                if not temp_layer.isValid():
                    print("Failed to create empty temporary memory layer")
                    return None

                # Start editing to add fields
                temp_layer.startEditing()
                data_provider = temp_layer.dataProvider()

                # Add fields
                original_fields = original_layer.fields()
                data_provider.addAttributes(original_fields)

                # Add UUID field
                uuid_field = QgsField("UUID", QVariant.String, "string", 38)
                data_provider.addAttributes([uuid_field])

                # Add SURVEYED field
                surveyed_field = QgsField("SURVEYED", QVariant.Bool, "bool")
                data_provider.addAttributes([surveyed_field])

                # Add any missing photo fields
                for photo_field in photo_fields:
                    if temp_layer.fields().indexFromName(photo_field) == -1:
                        data_provider.addAttributes([
                            QgsField(photo_field, QVariant.String, "string", 255)
                        ])

                # Add missing required fields
                if layer_attributes:
                    existing_names = [f.name().lower() for f in temp_layer.fields()]
                    for attr in layer_attributes:
                        if attr.lower() not in existing_names:
                            data_provider.addAttributes([QgsField(attr, QVariant.String, "string", 255)])

                temp_layer.updateFields()

                # Commit changes
                if not temp_layer.commitChanges():
                    print(f"Failed to commit changes for empty {layer_type} layer")
                    return None

                print(f"Successfully created empty {layer_type} layer")
                return temp_layer

            # For non-empty layers, process normally
            # Clip if needed
            working_layer = original_layer
            if clip_layer and clip_layer.isValid():
                try:
                    from qgis import processing # type: ignore
                    print(f"Clipping {original_layer.name()} with survey area polygon...")
                    
                    # Ensure both layers are in EPSG:31370 for clipping
                    if original_layer.crs().authid() != 'EPSG:31370':
                        # Reproject original layer to EPSG:31370
                        reprojected_result = processing.run("native:reprojectlayer", {
                            'INPUT': original_layer,
                            'TARGET_CRS': QgsCoordinateReferenceSystem('EPSG:31370'),
                            'OUTPUT': 'memory:'
                        })
                        original_layer = reprojected_result['OUTPUT']
                    
                    clipped_result = processing.run("native:clip", {
                        'INPUT': original_layer,
                        'OVERLAY': clip_layer,
                        'OUTPUT': 'memory:'
                    })
                    
                    working_layer = clipped_result['OUTPUT']
                    if working_layer.isValid():
                        print(f"Clipping successful: {working_layer.featureCount()} features")
                    else:
                        print("Clipping failed, using original layer")
                        working_layer = original_layer
                        
                except Exception as clip_error:
                    print(f"Processing clip failed: {clip_error}, using original layer")
                    working_layer = original_layer

            # SPECIAL PROCESSING FOR SIDEWALK LAYER - Split long segments
            is_sidewalk_layer = (layer_type == 'sidewalk')
            if is_sidewalk_layer and working_layer.geometryType() == QgsWkbTypes.LineGeometry:
                print("Processing sidewalk layer - splitting segments longer than 30 meters")
                # Use the split_long_sidewalk_segments function
                working_layer = self.split_long_sidewalk_segments(working_layer, max_length=30.0, target_crs=target_crs)
                if working_layer:
                    print(f"After splitting: {working_layer.featureCount()} features")

            # Create temporary layer in EPSG:31370
            temp_layer = QgsVectorLayer(
                f"{QgsWkbTypes.displayString(working_layer.wkbType())}?crs=EPSG:31370", 
                f"temp_{working_layer.name()}", 
                "memory"
            )

            if not temp_layer.isValid():
                print("Failed to create temporary memory layer")
                return None

            # Start editing
            temp_layer.startEditing()
            data_provider = temp_layer.dataProvider()

            # Copy fields
            original_fields = working_layer.fields()
            data_provider.addAttributes(original_fields)

            # Add UUID field
            uuid_field = QgsField("UUID", QVariant.String, "string", 38)
            data_provider.addAttributes([uuid_field])

            # Add SURVEYED field
            surveyed_field = QgsField("SURVEYED", QVariant.Bool, "bool")
            data_provider.addAttributes([surveyed_field])

            # Add any missing photo fields
            for photo_field in photo_fields:
                if temp_layer.fields().indexFromName(photo_field) == -1:
                    data_provider.addAttributes([
                        QgsField(photo_field, QVariant.String, "string", 255)
                    ])

            # Add missing required fields
            if layer_attributes:
                existing_names = [f.name().lower() for f in temp_layer.fields()]
                for attr in layer_attributes:
                    if attr.lower() not in existing_names:
                        data_provider.addAttributes([QgsField(attr, QVariant.String, "string", 255)])

            temp_layer.updateFields()

            # Copy features with coordinate transformation if needed
            features = []
            uuid_counter = 0
            
            # Check if we need to transform coordinates
            source_crs = working_layer.crs()
            need_transform = source_crs.isValid() and source_crs != target_crs
            
            for original_feature in working_layer.getFeatures():
                geometry = original_feature.geometry()
                
                if need_transform and not geometry.isEmpty():
                    try:
                        transform = QgsCoordinateTransform(source_crs, target_crs, QgsProject.instance())
                        geometry.transform(transform)
                    except Exception as transform_error:
                        print(f"Coordinate transformation failed: {transform_error}")

                new_feature = QgsFeature(temp_layer.fields())
                new_feature.setGeometry(geometry)

                # Copy all original attributes
                for field in original_fields:
                    field_name = field.name()
                    if field_name in original_feature.fields().names():
                        new_feature.setAttribute(field_name, original_feature[field_name])

                # Set new fields
                new_feature.setAttribute("UUID", str(uuid_counter))
                new_feature.setAttribute("SURVEYED", False)
                uuid_counter += 1

                features.append(new_feature)

            # Add all features
            if features:
                data_provider.addFeatures(features)

            # Commit changes
            if not temp_layer.commitChanges():
                print(f"Failed to commit changes for layer {working_layer.name()}")
                return None

            print(f"Created temporary layer with {temp_layer.featureCount()} features")
            return temp_layer

        except Exception as e:
            print(f"Error copying layer {original_layer.name() if original_layer else 'None'}: {e}")
            import traceback
            print(traceback.format_exc())
            if temp_layer and temp_layer.isValid() and temp_layer.isEditable():
                temp_layer.rollBack()
            return None

    def add_comment_field(self, layer):
        """Add a comment field to all layers."""
        if not layer or not layer.isValid():
            return

        # Check if comment field already exists
        fields = layer.fields()
        if fields.indexFromName("comment") != -1:
            print(f"Comment field already exists in layer: {layer.name()}")
            return

        # Start editing to add the comment field
        layer.startEditing()

        # Add comment field
        comment_field = QgsField("comment", QVariant.String, "string", 255)
        layer.addAttribute(comment_field)

        # Commit changes
        if not layer.commitChanges():
            print(f"Failed to add comment field to layer: {layer.name()}")
            layer.rollBack()
            return

        # Get the index of the new comment field
        fields = layer.fields()
        comment_idx = fields.indexFromName("comment")

        if comment_idx != -1:
            # Configure comment field as a text widget (multi-line text area)
            config = {
                'IsMultiline': True,
                'UseHtml': False
            }
            widget_setup = QgsEditorWidgetSetup("TextEdit", config)
            layer.setEditorWidgetSetup(comment_idx, widget_setup)

            print(f"Added and configured comment field for layer: {layer.name()}")
        else:
            print(f"Failed to find comment field index in layer: {layer.name()}")

    def hide_unneeded_fields(self, layer, layer_attributes, photo_fields):
        """Hide fields that are not in layer_attributes and not photo_fields."""
        if not layer or not layer.isValid():
            return

        # Combine fields that should be visible
        visible_fields = set(layer_attributes) | set(photo_fields) | {'UUID', 'SURVEYED', 'comment'}

        fields = layer.fields()
        for i, field in enumerate(fields):
            field_name = field.name()

            # Hide fields that are not in visible_fields
            if field_name not in visible_fields:
                # Set field as hidden using the Hidden editor widget
                widget_setup = QgsEditorWidgetSetup('Hidden', {})
                layer.setEditorWidgetSetup(i, widget_setup)
                print(f"Hidden field: {field_name} in layer {layer.name()}")

        layer.updateFields()
        print(f"Hidden unneeded fields for layer: {layer.name()}")

    def split_long_sidewalk_segments(self, layer, max_length=30.0, target_crs=None):
        """Split sidewalk segments longer than max_length into smaller segments using QGIS processing.

        If target_crs is provided and differs from layer.crs(), reproject the layer to target_crs
        first so that the LENGTH parameter (meters) is applied in linear units consistent with the
        project CRS.
        """

        if not layer or layer.geometryType() != QgsWkbTypes.LineGeometry:
            print("Invalid layer for splitting")
            return layer

        try:
            from qgis import processing  # type: ignore

            print(f"Splitting sidewalk segments longer than {max_length} meters...")

            layer_to_split = layer

            # Reproject to target_crs if provided and different - split algorithm uses layer units
            if target_crs and target_crs.isValid() and layer.crs().isValid() and layer.crs() != target_crs:
                try:
                    print(f"Reprojecting sidewalk layer from {layer.crs().authid()} to {target_crs.authid()} before splitting")
                    reproj_result = processing.run("native:reprojectlayer", {
                        'INPUT': layer,
                        'TARGET_CRS': target_crs,
                        'OUTPUT': 'memory:'
                    })
                    reproj_layer = reproj_result.get('OUTPUT')
                    if reproj_layer and reproj_layer.isValid():
                        layer_to_split = reproj_layer
                        print(f"Reprojection successful: {layer_to_split.crs().authid()}")
                    else:
                        print("Reprojection failed, will attempt to split original layer")
                except Exception as reproj_err:
                    print(f"Reprojection error: {reproj_err}, continuing with original layer")

            print(f"Feature count before split: {layer_to_split.featureCount()}")

            # Use QGIS native split by length algorithm
            result = processing.run("native:splitlinesbylength", {
                'INPUT': layer_to_split,
                'LENGTH': float(max_length),
                'OUTPUT': 'memory:'
            })

            split_layer = result.get('OUTPUT')

            if not split_layer or not split_layer.isValid():
                print("Splitting returned invalid layer - returning original")
                return layer

            # Ensure multipart parts are exploded to singlepart features (some inputs produce multipart)
            try:
                multi_to_single = processing.run("native:multiparttosingleparts", {
                    'INPUT': split_layer,
                    'OUTPUT': 'memory:'
                })
                single_layer = multi_to_single.get('OUTPUT')
                if single_layer and single_layer.isValid():
                    split_layer = single_layer
            except Exception:
                # Not fatal — keep split_layer as-is
                pass

            if split_layer and split_layer.isValid():
                print(f"Split successful: {split_layer.featureCount()} features after splitting")

                # Verify splitting worked by checking lengths (in layer units)
                long_segments_count = 0
                for feature in split_layer.getFeatures():
                    geom = feature.geometry()
                    if geom is None or geom.isEmpty():
                        continue
                    length = geom.length()
                    if length > max_length * 1.01:  # small tolerance
                        long_segments_count += 1
                        print(f"Long segment found: {length:.2f} (units of layer CRS)")

                if long_segments_count > 0:
                    print(f"Warning: {long_segments_count} segments still longer than {max_length} (layer units)")
                else:
                    print("All segments are within the maximum length limit")

                return split_layer
            else:
                print("Splitting failed - returning original layer")
                return layer

        except Exception as e:
            print(f"Error in split_long_sidewalk_segments: {e}")
            import traceback
            print(traceback.format_exc())
            return layer

    def configure_surveyed_field(self, layer):
        """Configure SURVEYED field as a checkbox with default value of 1 (checked)."""
        if not layer or not layer.isValid():
            return

        fields = layer.fields()
        surveyed_idx = fields.indexFromName("SURVEYED")

        if surveyed_idx == -1:
            print(f"SURVEYED field not found in layer: {layer.name()}")
            return

        # Configure as checkbox widget
        checkbox_config = {
            'CheckedState': True,
            'UncheckedState': False
        }
        widget_setup = QgsEditorWidgetSetup("CheckBox", checkbox_config)
        layer.setEditorWidgetSetup(surveyed_idx, widget_setup)

        print(f"Configured SURVEYED field as checkbox for layer: {layer.name()}")

    def configure_required_fields(self, layer, layer_type):
        """Configure required fields for each layer type with constraints and value maps."""
        if not layer or not layer.isValid():
            return

        # Define value maps for sidewalk subtypes - simpler dictionary structure
        value_maps = {
            'sidewalk': {
                'SUBTYPE': {
                    'Monoliete verharding': 'Monoliete verharding',
                    'Niet-monoliete verharding': 'Niet-monoliete verharding', 
                    'In berm': 'In berm'
                },
                'SUBTYPE2': {
                    'Asphalt black': 'Asphalt black',
                    'Asphalt colored': 'Asphalt colored',
                    'Concrete grey': 'Concrete grey',
                    'Concrete colored': 'Concrete colored',
                    'Decorative tiles': 'Decorative tiles',
                    'Clinkers': 'Clinkers',
                    'Dolomiet': 'Dolomiet',
                    'Grass grid in concrete': 'Grass grid in concrete',
                    'Grass grid in PVC': 'Grass grid in PVC',
                    'Open ground': 'Open ground'
                }
            }
        }

        required_fields_config = {
            'buildings': ['STREETNAME', 'INCLUDE'],
            'address': ['P2P_HOMES', 'INCLUDE', 'CITY', 'STREETNAME', 'BOX', 'POSTCODE', 'ADDRESS_NU'],
            'crossing': ['SUBTYPE'],
            'facade': ['SPAN', 'TRANSITION'],
            'sidewalk': ['SUBTYPE', 'STREETNAME', 'SUBTYPE2'],
            'pole': ['INCLUDE', 'LOCKED']
        }

        fields = layer.fields()

        # SPECIAL HANDLING FOR SIDEWALK LAYER: Ensure SUBTYPE2 field exists
        if layer_type == 'sidewalk':
            subtype2_idx = fields.indexFromName("SUBTYPE2")
            if subtype2_idx == -1:
                print(f"SUBTYPE2 field not found in sidewalk layer. Adding it...")

                # Start editing to add the field
                layer.startEditing()

                # Add SUBTYPE2 field
                subtype2_field = QgsField("SUBTYPE2", QVariant.String, "string", 50)
                layer.addAttribute(subtype2_field)

                # Commit changes
                if not layer.commitChanges():
                    print(f"Failed to add SUBTYPE2 field to sidewalk layer: {layer.name()}")
                    layer.rollBack()
                else:
                    print(f"Successfully added SUBTYPE2 field to sidewalk layer")
                    # Refresh fields reference
                    fields = layer.fields()

        for i, field in enumerate(fields):
            field_name = field.name()

            # Apply value map if defined for this layer_type and field
            if layer_type in value_maps and field_name in value_maps[layer_type]:
                print(f"Applying value map to field '{field_name}' in {layer_type} layer")

                # Use the dictionary directly as the map
                widget_config = {
                    'map': value_maps[layer_type][field_name]
                }

                widget_setup = QgsEditorWidgetSetup("ValueMap", widget_config)
                layer.setEditorWidgetSetup(i, widget_setup)

            # Set field as required if in config
            if field_name in required_fields_config.get(layer_type, []):
                print(f"Setting field '{field_name}' as required for layer: {layer.name()}")

                # Not-null hard constraint
                layer.setFieldConstraint(
                    i,
                    QgsFieldConstraints.ConstraintNotNull,
                    QgsFieldConstraints.ConstraintStrengthHard
                )

                # Also set unique constraint if it's an ID field
                if any(id_keyword in field_name.upper() for id_keyword in ['ID', 'UUID', 'IDENTIFIER']):
                    layer.setFieldConstraint(
                        i,
                        QgsFieldConstraints.ConstraintUnique,
                        QgsFieldConstraints.ConstraintStrengthHard
                    )

        # Ensure the layer updates in the interface
        layer.updateFields()
        layer.triggerRepaint()
        print(f"Configured fields for layer: {layer.name()}")

    def configure_photo_fields(self, layer):
        """Configure photo fields to use Attachment widget with directory path storage."""
        if not layer or not layer.isValid():
            return

        # Define the field names to look for
        target_fields = ['photo','mdu', 'photostart', 'photoend']

        # Get layer's fields
        fields = layer.fields()
        for i, field in enumerate(fields):
            field_name = field.name()

            # Check if this field is one of our target photo fields
            if field_name.lower() in target_fields:
                print(f"Configuring field '{field_name}' as photo attachment...")

                # Configure as Attachment widget with directory path storage
                config = {
                    'RelativeStorage': 0,  # 0 = Absolute path
                    'StorageMode': 1,      # 1 = File paths (directory)
                    'DocumentViewer': 1,
                    'DocumentViewerHeight': 0,
                    'DocumentViewerWidth': 0,
                    'FileWidget': True,
                    'FileWidgetButton': True,
                    'FileWidgetFilter': "Images (*.png *.jpg *.jpeg *.bmp *.gif *.tif *.tiff);;All files (*)",
                    'UseLink': True,
                    'DefaultRoot': '',  # Empty for absolute paths
                    'StoreAbsolutePath': True  # Store absolute paths
                }

                widget_setup = QgsEditorWidgetSetup("ExternalResource", config)
                layer.setEditorWidgetSetup(i, widget_setup)

                 # Set expression for file name based on uuid field
                if "uuid" in [f.name().lower() for f in fields]:
                    naming_expression = '"uuid" || \'.jpg\''
                else:
                    naming_expression = 'format_date(now(), \'yyyyMMdd_hhmmss\') || \'.jpg\''

                # Field name for attachment naming — usually "path" or "photo"
                attachment_field = "photo"

                # Store it in the same property QField uses internally
                layer.setCustomProperty("QFieldSync/photo_naming_field", attachment_field)
                layer.setCustomProperty("QFieldSync/photo_naming_expression", naming_expression)
                layer.setCustomProperty("QFieldSync/photo_naming_active", True)

                # Set constraints — MDU field is optional, others are required
                if field_name.lower() != 'mdu':
                    layer.setFieldConstraint(
                        i,
                        QgsFieldConstraints.ConstraintNotNull,
                        QgsFieldConstraints.ConstraintStrengthHard
                    )
                else:
                    print(f"Field '{field_name}' set as OPTIONAL (no not-null constraint)")

        layer.updateFields()
        print(f"Configured photo fields for layer: {layer.name()}")

    def apply_surveyed_symbology(self, layer):
        """Apply rule-based symbology to distinguish surveyed vs unsurveyed features."""
        if not layer or not layer.isValid():
            return

        geom_type = layer.geometryType()

        # Define colors
        surveyed_color = '46,204,113,255'      # Green for surveyed
        unsurveyed_color = '231,76,60,255'     # Red for unsurveyed

        # Define colors for buildings
        surveyed_color_bd = '0,70,200,255'     # Blue for surveyed
        unsurveyed_color_bd = '200,200,0,255'     # Yellow for unsurveyed

        # Create root rule
        root_rule = QgsRuleBasedRenderer.Rule(None)

        # Rule for surveyed features (SURVEYED = 1)
        if geom_type == QgsWkbTypes.PolygonGeometry:
            surveyed_symbol = QgsFillSymbol.createSimple({
                'color': surveyed_color_bd,
                'outline_color': '0,70,200,255',
                'outline_width': '0.5',
                'outline_style': 'solid'
            })
            unsurveyed_symbol = QgsFillSymbol.createSimple({
                'color': unsurveyed_color_bd,
                'outline_color': '200,200,0,255',
                'outline_width': '0.5',
                'outline_style': 'solid'
            })
        elif geom_type == QgsWkbTypes.LineGeometry:
            surveyed_symbol = QgsLineSymbol.createSimple({
                'color': surveyed_color,
                'width': '1.0',
                'line_style': 'solid'
            })
            unsurveyed_symbol = QgsLineSymbol.createSimple({
                'color': unsurveyed_color,
                'width': '1.0',
                'line_style': 'solid'
            })
        elif geom_type == QgsWkbTypes.PointGeometry:
            surveyed_symbol = QgsMarkerSymbol.createSimple({
                'color': surveyed_color,
                'outline_color': '39,174,96,255',
                'size': '4',
                'name': 'circle'
            })
            unsurveyed_symbol = QgsMarkerSymbol.createSimple({
                'color': unsurveyed_color,
                'outline_color': '192,57,43,255',
                'size': '4',
                'name': 'circle'
            })
        else:
            print(f"Unknown geometry type for layer: {layer.name()}")
            return

        # Create rules
        surveyed_rule = QgsRuleBasedRenderer.Rule(surveyed_symbol)
        surveyed_rule.setFilterExpression('"SURVEYED" = 1')
        surveyed_rule.setLabel('Surveyed')

        unsurveyed_rule = QgsRuleBasedRenderer.Rule(unsurveyed_symbol)
        unsurveyed_rule.setFilterExpression('"SURVEYED" = 0 OR "SURVEYED" IS NULL')
        unsurveyed_rule.setLabel('Not Surveyed')

        # Add rules to root
        root_rule.appendChild(surveyed_rule)
        root_rule.appendChild(unsurveyed_rule)

        # Create and apply renderer
        renderer = QgsRuleBasedRenderer(root_rule)
        layer.setRenderer(renderer)
        layer.triggerRepaint()

        print(f"Applied surveyed symbology to layer: {layer.name()}")

    def apply_red_outline_style(self, layer):
        """Apply solid red border with transparent fill to a polygon layer."""
        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            return

        symbol = QgsFillSymbol.createSimple({
            'color': '0,0,0,0',
            'outline_color': '228,26,28,255',
            'outline_width': '0.96',
            'outline_style': 'solid'
        })

        renderer = QgsSingleSymbolRenderer(symbol)
        layer.setRenderer(renderer)
        layer.triggerRepaint()
        print(f"Applied red outline style to layer: {layer.name()}")

    def apply_buildings_style(self, layer):
        """Apply a distinct style for buildings layer."""
        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            return

        symbol = QgsFillSymbol.createSimple({
                'color': '0,70,200,255',
                'outline_color': '0,70,200,255',
                'outline_width': '0.5',
                'outline_style': 'solid'
            })

        renderer = QgsSingleSymbolRenderer(symbol)
        layer.setRenderer(renderer)
        layer.triggerRepaint()
        print(f"Applied buildings style to layer: {layer.name()}")

    def apply_striped_symbology(self, layer):
        """Apply striped symbology to a polygon layer."""
        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            print(f"Layer {layer.name()} is not a polygon layer, skipping striped symbology")
            return

        # Create a fill symbol
        symbol = QgsFillSymbol.createSimple({})

        # Remove default layers
        for i in range(symbol.symbolLayerCount()):
            symbol.deleteSymbolLayer(0)

        # Add a solid fill as base layer
        simple_fill = QgsSimpleFillSymbolLayer()
        simple_fill.setFillColor(QColor(0, 70, 200, 100))  # Light blue with transparency
        simple_fill.setStrokeColor(QColor(0, 70, 200, 255))
        simple_fill.setStrokeWidth(0.5)
        symbol.appendSymbolLayer(simple_fill)

        # Add line pattern fill for stripes
        line_pattern_fill = QgsLinePatternFillSymbolLayer()
        line_pattern_fill.setLineAngle(45)  # 45 degree angle for stripes
        line_pattern_fill.setDistance(3.0)  # Distance between lines

        # Create a line symbol for the pattern and set its properties
        line_symbol = line_pattern_fill.subSymbol()
        if line_symbol:
            line_symbol.setWidth(1.0)  # Width of stripe lines
            line_symbol.setColor(QColor(0, 70, 200, 255))  # Stripe color

        # Add the line pattern as another symbol layer
        symbol.appendSymbolLayer(line_pattern_fill)

        # Apply the symbol to the layer
        renderer = QgsSingleSymbolRenderer(symbol)
        layer.setRenderer(renderer)
        layer.triggerRepaint()

        print(f"Applied striped symbology to layer: {layer.name()}")

    def setup_auto_xy_from_project_crs(self, layer, project_crs):
        """Configure read-only X/Y (LON/LAT) fields and auto-fill using WGS84 (EPSG:4326) coordinates.
        Assumes the layer is a point layer and uses the point geometry directly."""
        if not layer or not layer.isValid():
            print("Auto XY setup skipped: invalid layer")
            return

        # find LAT / LON (or X/Y) field indices (case-insensitive)
        fields = layer.fields()
        lat_idx = None
        lon_idx = None
        for i, f in enumerate(fields):
            n = f.name().lower()
            if n in ('lat', 'latitude', 'y'):
                lat_idx = i
            if n in ('lon', 'lng', 'long', 'longitude', 'x'):
                lon_idx = i

        if lat_idx is None or lon_idx is None:
            print("Address layer missing LAT/LON (or X/Y) fields; auto-fill disabled.")
            return

        # Set default values using expressions based on geometry transformed to WGS84
        try:
            # Get the layer's CRS auth ID
            layer_crs_authid = layer.crs().authid() if layer.crs().isValid() else 'EPSG:4326'
            target_crs = 'EPSG:4326'  # Always use WGS84 for LAT/LON
            
            # Build expressions that transform geometry to EPSG:4326 before extracting coordinates
            if layer_crs_authid != target_crs:
                # Need to transform geometry to WGS84
                lon_expression = f"x(transform($geometry, '{layer_crs_authid}', '{target_crs}'))"
                lat_expression = f"y(transform($geometry, '{layer_crs_authid}', '{target_crs}'))"
                print(f"Using transformation: {layer_crs_authid} -> {target_crs}")
            else:
                # No transformation needed, already in WGS84
                lon_expression = "x($geometry)"
                lat_expression = "y($geometry)"
                print(f"No CRS transformation needed, layer already in: {target_crs}")

            # Set default value expressions that will be evaluated when the feature is created
            layer.setDefaultValueDefinition(lon_idx, 
                QgsDefaultValue(lon_expression, True))

            layer.setDefaultValueDefinition(lat_idx, 
                QgsDefaultValue(lat_expression, True))

            print(f"Set default value expressions for LAT/LON fields using WGS84 (EPSG:4326)")
        except Exception as e:
            print(f"Could not set default value expressions: {e}")

        # Mark the fields read-only in the form
        try:
            ro_setup = QgsEditorWidgetSetup('TextEdit', {'ReadOnly': True})
            layer.setEditorWidgetSetup(lat_idx, ro_setup)
            layer.setEditorWidgetSetup(lon_idx, ro_setup)
        except Exception as e:
            print(f"Could not set editor widgets to read-only: {e}")

        print(f"Auto X/Y setup complete for layer: {layer.name()} (storing as EPSG:4326)")