# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesignValidationToolDialog
                                 A QGIS plugin
 This project involves the development of a specialized plugin for QGIS that automates the validation of a fiber optic network design against a critical set of predefined business and technical  rules. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hamza Bouhali & Musa Haruna / M.design solutions
        email                : info@mdesignsolutions.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from qgis.PyQt import QtWidgets, uic  # type: ignore
from qgis.PyQt.QtCore import (QFile, QTextStream, QTimer) # type: ignore

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'design_validation_tool_dialog_base.ui'))

class DesignValidationToolDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DesignValidationToolDialog, self).__init__(parent)
        self.setupUi(self)

        self.is_processing = False  # Flag to indicate if processing is ongoing
        self.setup_progress_bar()

        # Apply custom style for the OK and Cancel buttons
        
        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)
        if ok_btn:
            ok_btn.setStyleSheet("""
                background-color: #1f3a52;
                color: #fff;
                padding: 6px 12px;
                border-radius: 8px;
                border: none;
                width: 60px;
                font-weight: bold;
                height: 15px;
            """)
            ok_btn.setText("Run")
        if cancel_btn:
            cancel_btn.setStyleSheet("""
                background-color: #e8eaed;
                color: #2e3440;
                padding: 6px 12px;
                border-radius: 8px;
                border: 1px solid #d0d7dc;
                width: 60px;
                font-weight: bold;
                height: 15px;
            """)
            cancel_btn.setText("Close")
        # ===== APPLY STYLE SHEET =====
        self.apply_stylesheet()

        # Connect the OK button to the validation function
        self.button_box.accepted.connect(self.validate_inputs)
        self.button_box.rejected.connect(self.reject)

    def setup_progress_bar(self):
        """Set up the progress bar"""
        if hasattr(self, 'progressBar'):
            self.progressBar.setValue(0)
            self.progressBar.setVisible(False)
            self.progressBar.setRange(0, 100)

            self.progressBar.setStyleSheet("""
            QProgressBar {
                border: 2px solid #2e3440;
                border-radius: 8px;
                background-color: #e8eaed;
                text-align: center;
                font-weight: bold;
                font-size: 14px;
                color: white;
                text-shadow: 
                    -2px -2px 0 #000,  
                    2px -2px 0 #000,
                    -2px 2px 0 #000,
                    2px 2px 0 #000,
                    -1px 0 0 #000,
                    1px 0 0 #000,
                    0 -1px 0 #000,
                    0 1px 0 #000;
            }
            
            QProgressBar::chunk {
                background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,
                    stop: 0 #1f3a52, stop: 1 #2e4d68);
                border-radius: 6px;
                margin: 1px;
            }
        """)

    def start_processing(self):
        """Start processing and show the progress bar"""
        self.is_processing = True
        self.progressBar.setVisible(True)
        self.progressBar.setValue(0)

        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)

        if ok_btn:
            ok_btn.setEnabled(False)
        if cancel_btn:
            cancel_btn.setText("Processing...")
            cancel_btn.setEnabled(False)

    def update_progress(self, value):
        """Update the progress bar value"""
        self.progressBar.setValue(value)
        QtWidgets.QApplication.processEvents()
    
    def finish_processing(self):
        """Finish processing and hide the progress bar"""
        self.is_processing = False
        self.progressBar.setValue(100)

        ok_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_btn = self.button_box.button(QtWidgets.QDialogButtonBox.Cancel)

        if ok_btn:
            ok_btn.setEnabled(True)
        if cancel_btn:
            cancel_btn.setText("Close")
            cancel_btn.setEnabled(True)

        QTimer.singleShot(1000, lambda: self.progressBar.setVisible(False))
        QTimer.singleShot(500, self.clear_inputs)

    def closeEvent(self, event):
        """Handle the close event"""
        if self.is_processing:
            QtWidgets.QMessageBox.warning(
                self,
                "Warning",
                "Processing is ongoing. Please wait until it finishes."
            )
        else:
            event.accept()

    def reject(self):
        """Override reject to prevent closing during processing"""
        if self.is_processing:
            QtWidgets.QMessageBox.warning(
                self,
                "Warning",
                "Processing is ongoing. Please wait until it finishes."
            )
            return
        super(DesignValidationToolDialog, self).reject()

    def apply_stylesheet(self):
        # Path to your style.qss file (adjust path as needed)
        style_path = os.path.join(os.path.dirname(__file__), 'style.qss')

        if os.path.exists(style_path):
            style_file = QFile(style_path)
            if style_file.open(QFile.ReadOnly | QFile.Text):
                stream = QTextStream(style_file)
                style_sheet = stream.readAll()
                self.setStyleSheet(style_sheet)
                style_file.close()
            else:
                QtWidgets.QMessageBox.warning(self, "Warning", "Warning: Could not open style.qss")
        else:
            QtWidgets.QMessageBox.warning(self, "Warning", f"Warning: style.qss not found at {style_path}")

    def validate_inputs(self):
        """Validate inputs before accepting the dialog"""
        project_file_path = self.designSessionProjectFile.filePath()
        output_directory = self.OutputDirectoryOfGeneratedReports.filePath()

        # Basic validation
        if not project_file_path:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select a design session project file.")
            return
            
        if not output_directory:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select an output directory.")
            return
            
        if not self.get_selected_checks():
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select at least one validation check.")
            return
        self.accept()

    def get_zip_file_path(self):
        """Get the selected zip file path"""
        return self.designSessionZipFile.filePath()
    
    def get_project_file_path(self):
        """Get the selected zip file path"""
        return self.designSessionProjectFile.filePath()
    
    def get_output_directory(self):
        """Get the selected output directory"""
        return self.OutputDirectoryOfGeneratedReports.filePath()
    
    def get_selected_checks(self):
        """Get a dictionary of selected validation checks"""
        return {
            'poc_clustering': self.pocChecker.isChecked(),
            'overlap': self.overlapChecker.isChecked(),
            'primary_distribution': self.primaryDistributionChecker.isChecked(),
            'crossings': self.crossingsChecker.isChecked(),
            'feeder': self.feederChecker.isChecked(),
            'distribution': self.distributionChecker.isChecked(),
            'data_quality': self.data_qualityChecker.isChecked(),
            'trenches': self.trenchChecker.isChecked(),
            'generate_report': self.generateReportCheckbox.isChecked()
        }
    
    def clear_inputs(self):
        """Clear all input fields and checkboxes"""
        # Clear file paths
        if hasattr(self, 'designSessionProjectFile'):
            self.designSessionProjectFile.setFilePath('')
        
        if hasattr(self, 'designSessionZipFile'):
            self.designSessionZipFile.setFilePath('')
        
        if hasattr(self, 'OutputDirectoryOfGeneratedReports'):
            self.OutputDirectoryOfGeneratedReports.setFilePath('')
        
        # Uncheck all validation checkboxes
        if hasattr(self, 'pocChecker'):
            self.pocChecker.setChecked(False)
        
        if hasattr(self, 'overlapChecker'):
            self.overlapChecker.setChecked(False)
        
        if hasattr(self, 'primaryDistributionChecker'):
            self.primaryDistributionChecker.setChecked(False)

        if hasattr(self, 'feederChecker'):
            self.feederChecker.setChecked(False)
        
        if hasattr(self, 'distributionChecker'):
            self.distributionChecker.setChecked(False)

        if hasattr(self, 'data_qualityChecker'):
            self.data_qualityChecker.setChecked(False)

        if hasattr(self, 'crossingsChecker'):
            self.crossingsChecker.setChecked(False)
        
        if hasattr(self, 'trenchChecker'):
            self.trenchChecker.setChecked(False)


    def validate_inputs_only(self):
        """Validate inputs without closing dialog - returns True if valid"""
        project_file_path = self.designSessionProjectFile.filePath()
        output_directory = self.OutputDirectoryOfGeneratedReports.filePath()

        if not project_file_path:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select a design session project file.")
            return False
            
        if not output_directory:
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select an output directory.")
            return False
            
        if not self.get_selected_checks():
            QtWidgets.QMessageBox.warning(self, "Warning", "Please select at least one validation check.")
            return False
        
        return True