# -*- coding: utf-8 -*-
"""
/***************************************************************************
ImageIdentifyTool
                                A QGIS plugin
Image Identify Tool
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                            -------------------
        begin                : 2025-10-30
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hamza BOUHALI & Musa HAROUNA / M.designsolutions
        email                : info@mdesignsolutions.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt # type: ignore
from qgis.PyQt.QtGui import QIcon # type: ignore
from qgis.PyQt.QtWidgets import QAction # type: ignore

from .imageidentifytool_dialog import ImageIdentifyDockWidget
from .image_identify_tool import ImageIdentifyMapTool


class ImageIdentifyTool:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.canvas = iface.mapCanvas()
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ImageIdentifyTool_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Image Identify Tool')

        # Plugin components
        self.dock_widget = None
        self.identify_tool = None
        self.action = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('ImageIdentifyTool', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.action = self.add_action(
            icon_path,
            text=self.tr(u'Image Identify Tool'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.action.setCheckable(True)

        # Create the dock widget
        self.dock_widget = ImageIdentifyDockWidget()
        self.dock_widget.setAllowedAreas(Qt.LeftDockWidgetArea | Qt.RightDockWidgetArea)

        # Create the map tool
        self.identify_tool = ImageIdentifyMapTool(self.canvas, self.dock_widget)
        self.identify_tool.setAction(self.action)

        # Connect dock widget visibility changes
        self.dock_widget.visibilityChanged.connect(self.on_dock_visibility_changed)

    def get_actions(self):
        return self.actions

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.deactivate_tool()

        # Remove dock widget
        if self.dock_widget:
            self.iface.removeDockWidget(self.dock_widget)
            self.dock_widget.deleteLater()
            self.dock_widget = None

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Image Identify Tool'),
                action)

    def deactivate_tool(self):
        """Deactivate the identify tool."""
        if self.identify_tool:
            self.canvas.unsetMapTool(self.identify_tool)
        if self.action:
            self.action.setChecked(False)

    def on_dock_visibility_changed(self, visible):
        """Handle dock widget visibility changes."""
        if not visible and self.action:
            self.action.setChecked(False)
            self.deactivate_tool()

    def run(self):
        """Run method that performs all the real work"""
        if self.action.isChecked(): # type: ignore
            # Activate the tool and show dock
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dock_widget)
            self.dock_widget.show() # type: ignore
            self.canvas.setMapTool(self.identify_tool)
        else:
            # Deactivate the tool
            self.deactivate_tool()