# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImageIdentifyToolDialog
                                 A QGIS plugin
 Image Identify Tool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-30
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Hamza BOUHALI & Musa HAROUNA / M.designsolutions
        email                : info@mdesignsolutions.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from pathlib import Path

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt, pyqtSignal, QSize
from qgis.PyQt import QtCore
from qgis.PyQt.QtGui import QPixmap, QTransform, QCursor
from qgis.PyQt.QtWidgets import QLabel

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "imageidentifytool_dialog_base.ui")
)


class ClickableLabel(QLabel):
    """A clickable QLabel that emits a signal when clicked."""

    clicked = pyqtSignal(str, object)  # field_name, field_value

    def __init__(self, text, field_name, field_value, parent=None):
        super().__init__(text, parent)
        self.field_name = field_name
        self.field_value = field_value
        self.setStyleSheet("color: blue; text-decoration: underline; cursor: pointer;")
        self.setCursor(Qt.PointingHandCursor)
        self.setToolTip(f"Click to open image: {field_value}")

    def mousePressEvent(self, event):
        """Handle mouse click events."""
        try:
            self.clicked.emit(self.field_name, self.field_value)
            event.accept()
        except Exception:
            super().mousePressEvent(event)


class ImageIdentifyDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ImageIdentifyDockWidget, self).__init__(parent)
        self.setupUi(self)

        # Store references to image tabs and labels
        self.image_tabs = {}  # field_name -> (tab, scroll_area, image_label)

        # Store current zoom and rotation state for each image
        self.image_states = (
            {}
        )  # field_name -> {'zoom': float, 'rotation': int, 'original_pixmap': QPixmap}

        # Track manual zoom state
        self.manual_zoom_active = False

        #  ADD PANNING VARIABLES 
        self.dragging = False
        self.drag_start_global = None
        self.drag_label_start_pos = None
        self.current_panning_field = None

        # Configure the table
        self.configure_table()

        # Connect signals
        self.attributeTable.itemSelectionChanged.connect(self.on_attribute_selected)
        self.imageTabWidget.currentChanged.connect(self.on_tab_changed)

        # Connect zoom and rotate buttons
        self.zoomInButton.clicked.connect(self.zoom_in)
        self.zoomOutButton.clicked.connect(self.zoom_out)
        self.rotateButton.clicked.connect(self.rotate_image)
        self.resetButton.clicked.connect(self.reset_image)

        # Connect main tab change to switch to image gallery when photo links are clicked
        self.mainTabWidget.currentChanged.connect(self.on_main_tab_changed)

    def configure_table(self):
        """Configure the attribute table appearance."""
        # Set table properties
        self.attributeTable.setColumnWidth(0, 150)  # Field column width
        self.attributeTable.setColumnWidth(1, 200)  # Value column width

        # Make table read-only
        self.attributeTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        # Enable word wrap for value column
        self.attributeTable.horizontalHeader().setStretchLastSection(True)

    def clear_display(self):
        """Clear all displayed information."""
        self.attributeTable.setRowCount(0)
        self.clear_image_tabs()
        self.imageInfoLabel.setText("Select an image tab to view details")
        self.image_states.clear()
        self.manual_zoom_active = False
        #  RESET PANNING STATE 
        self.dragging = False
        self.current_panning_field = None

    def clear_image_tabs(self):
        """Remove all image tabs except the default 'No Images' tab."""
        # Remove all tabs except the first one (No Images tab)
        while self.imageTabWidget.count() > 1:
            self.imageTabWidget.removeTab(1)

        self.image_tabs.clear()

        # Show the no images tab
        self.imageTabWidget.setCurrentIndex(0)

    def display_feature_info(self, feature, layer):
        """Display feature attributes in a table and find all image fields."""
        self.attributeTable.setRowCount(0)
        self.clear_image_tabs()
        self.image_states.clear()
        self.manual_zoom_active = False
        self.dragging = False
        self.current_panning_field = None

        fields = layer.fields()
        image_fields = []
        row = 0

        # First pass: collect all attributes and identify image fields
        for field in fields:
            field_name = field.name()
            field_value = feature[field_name]

            # Skip geometry fields and None values
            if (
                field_name.lower() in ["geometry", "geom", "shape"]
                or field_value is None
            ):
                continue

            # Add row to table
            self.attributeTable.insertRow(row)

            # Field name cell
            field_item = QtWidgets.QTableWidgetItem(field_name)
            field_item.setData(Qt.UserRole, (field_name, field_value))
            self.attributeTable.setItem(row, 0, field_item)

            # Field value cell - create clickable link for image fields
            value_text = str(field_value)
            if value_text == "NULL" or value_text == "":
                value_text = "NULL"
                value_item = QtWidgets.QTableWidgetItem(value_text)
                value_item.setForeground(Qt.gray)  # Make NULL values gray
                self.attributeTable.setItem(row, 1, value_item)
            else:
                # Check if this is an image field
                if self.is_image_field(field_name, field_value):
                    # Create a clickable label for image fields
                    value_widget = QtWidgets.QWidget()
                    value_layout = QtWidgets.QHBoxLayout(value_widget)
                    value_layout.setContentsMargins(2, 2, 2, 2)

                    clickable_label = ClickableLabel("View Image", field_name, field_value)
                    clickable_label.clicked.connect(self.on_image_link_clicked)
                    value_layout.addWidget(clickable_label)
                    value_layout.addStretch()

                    self.attributeTable.setCellWidget(row, 1, value_widget)
                    value_item = QtWidgets.QTableWidgetItem()  # Empty item for the cell
                    self.attributeTable.setItem(row, 1, value_item)

                    image_fields.append((field_name, field_value))
                    # Highlight the row for image fields
                    field_item.setBackground(Qt.lightGray)
                else:
                    value_item = QtWidgets.QTableWidgetItem(value_text)
                    value_item.setData(Qt.UserRole, (field_name, field_value))
                    self.attributeTable.setItem(row, 1, value_item)

            row += 1

        # Resize rows to content
        self.attributeTable.resizeRowsToContents()

        # Create tabs for each image field
        for field_name, field_value in image_fields:
            self.create_image_tab(field_name, field_value)

        # If we have images, select the first one and switch to image gallery tab
        if image_fields:
            self.imageTabWidget.setCurrentIndex(1)  # Skip the "No Images" tab
            self.display_image(image_fields[0][0], image_fields[0][1])

    def on_attribute_selected(self):
        """Handle attribute table selection changes."""
        selected_items = self.attributeTable.selectedItems()
        if selected_items:
            item = selected_items[0]  # Get first selected item
            if item.data(Qt.UserRole):
                field_name, field_value = item.data(Qt.UserRole)
                # If this attribute has an image tab, switch to image gallery and select the tab
                if field_name in self.image_tabs:
                    self.mainTabWidget.setCurrentIndex(1)  # Switch to Image Gallery tab
                    tab_index = list(self.image_tabs.keys()).index(field_name) + 1  # +1 for "No Images" tab
                    self.imageTabWidget.setCurrentIndex(tab_index)

    def on_image_link_clicked(self, field_name, field_value):
        """Handle click on image link in the attribute table."""
        # Open image in system viewer
        self.open_image_in_system_viewer(field_value)

        # Also switch to Image Gallery tab and select the corresponding image tab
        self.mainTabWidget.setCurrentIndex(1)

        # Find and select the corresponding image tab
        if field_name in self.image_tabs:
            tab_index = list(self.image_tabs.keys()).index(field_name) + 1  # +1 for "No Images" tab
            self.imageTabWidget.setCurrentIndex(tab_index)
            self.display_image(field_name, field_value)

    def on_main_tab_changed(self, index):
        """Handle main tab changes."""
        if index == 1:  # Image Gallery tab
            # If no images are loaded but we have image fields, load the first one
            if (self.imageTabWidget.currentIndex() == 0 and 
                self.image_tabs and 
                len(self.image_tabs) > 0):
                first_field = list(self.image_tabs.keys())[0]
                self.imageTabWidget.setCurrentIndex(1)
                self.display_image(first_field, self.image_tabs[first_field][3])

    def is_image_field(self, field_name, field_value):
        """Check if a field might contain image paths/URLs."""
        if not field_value:
            return False

        str_value = str(field_value).strip()
        if not str_value or str_value == "NULL":
            return False

        # Check field name patterns
        image_field_names = [
            "photo", "image", "picture", "img", "myphoto", "foto",
            "photograph", "photo_path", "image_path", "picture_path",
            "url", "link", "attachment", "start", "end", "before", "after",
            "left", "right", "front", "back", "side", "top", "bottom",
        ]
        if any(img_name in field_name.lower() for img_name in image_field_names):
            return True

        # Check value patterns for image extensions
        image_extensions = [
            ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp",
        ]
        if any(str_value.lower().endswith(ext) for ext in image_extensions):
            return True

        # Check for URL patterns
        if str_value.startswith(("http://", "https://", "file://", "www.")):
            return True

        # Check for common path patterns
        if "/" in str_value or "\\" in str_value:
            return True

        return False

    def create_image_tab(self, field_name, field_value):
        """Create a new tab for an image field with resizable image area."""
        # Create tab and widget
        tab = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(tab)
        layout.setContentsMargins(2, 2, 2, 2)

        # Create scroll area for image with resizing
        scroll_area = QtWidgets.QScrollArea()
        scroll_area.setWidgetResizable(False)  #  ALWAYS FALSE 
        scroll_area.setAlignment(Qt.AlignCenter)
        scroll_area.setMinimumSize(200, 150)

        #  COMPLETELY DISABLE SCROLLBARS - NO WHEEL SCROLLING 
        scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        #  ENABLE MOUSE TRACKING FOR PANNING 
        scroll_area.setMouseTracking(True)
        scroll_area.viewport().setMouseTracking(True)

        # Create image label
        image_label = QtWidgets.QLabel()
        image_label.setAlignment(Qt.AlignCenter)
        image_label.setMinimumSize(200, 150)
        image_label.setStyleSheet(
            """
            QLabel {
                background-color: #f0f0f0; 
                border: 2px solid #ccc;
                border-radius: 4px;
            }
        """
        )
        image_label.setText("Loading image...")
        image_label.setScaledContents(False)

        #  ENABLE MOUSE TRACKING ON LABEL 
        image_label.setMouseTracking(True)

        scroll_area.setWidget(image_label)
        layout.addWidget(scroll_area)

        # Add tab to tab widget
        display_name = self.get_display_name(field_name)
        tab_index = self.imageTabWidget.addTab(tab, display_name)
        self.image_tabs[field_name] = (tab, scroll_area, image_label, field_value)

        # Initialize image state
        self.image_states[field_name] = {
            "zoom": 1.0,
            "rotation": 0,
            "original_pixmap": None,
            "pan_x": 0,  # ADD PAN OFFSET 
            "pan_y": 0   # ADD PAN OFFSET 
        }

        #  INSTALL EVENT FILTER FOR MOUSE EVENTS 
        scroll_area.viewport().installEventFilter(self)
        image_label.installEventFilter(self)

        # Load the image
        self.load_and_display_image(field_name)

    def get_display_name(self, field_name):
        """Get a user-friendly display name for the field."""
        # Convert field name to title case and replace underscores
        display_name = field_name.replace("_", " ").title()

        # Shorten very long names
        if len(display_name) > 15:
            display_name = display_name[:15] + "..."

        return display_name

    def get_current_image_field(self):
        """Get the field name of the currently displayed image."""
        current_index = self.imageTabWidget.currentIndex()
        if current_index == 0:  # "No Images" tab
            return None

        field_names = list(self.image_tabs.keys())
        if current_index - 1 < len(field_names):
            return field_names[current_index - 1]
        return None

    def zoom_in(self):
        """Zoom in on the current image."""
        field_name = self.get_current_image_field()
        if not field_name or field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        if not state["original_pixmap"]:
            return

        # Activate manual zoom
        self.manual_zoom_active = True

        # Smooth 25% zoom in
        state["zoom"] = min(state["zoom"] * 1.25, 10.0)
        self.apply_image_transformations(field_name)

    def zoom_out(self):
        """Zoom out from the current image."""
        field_name = self.get_current_image_field()
        if not field_name or field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        if not state["original_pixmap"]:
            return

        # Activate manual zoom
        self.manual_zoom_active = True

        # Smooth 25% zoom out
        state["zoom"] = max(state["zoom"] * 0.75, 0.05)
        self.apply_image_transformations(field_name)

    def rotate_image(self):
        """Rotate the current image 90 degrees clockwise."""
        field_name = self.get_current_image_field()
        if not field_name or field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        if not state["original_pixmap"]:
            return

        # Rotate 90 degrees clockwise
        state["rotation"] = (state["rotation"] + 90) % 360
        self.apply_image_transformations(field_name)

    def reset_image(self):
        """Reset zoom and rotation for current image."""
        field_name = self.get_current_image_field()
        if not field_name or field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        if not state["original_pixmap"]:
            return

        # Reset to auto-fit mode
        state["zoom"] = 1.0
        state["rotation"] = 0
        state["pan_x"] = 0  # RESET PAN OFFSET 
        state["pan_y"] = 0  # RESET PAN OFFSET 
        self.manual_zoom_active = False
        self.apply_image_transformations(field_name)

    def apply_image_transformations(self, field_name):
        """Apply current zoom and rotation to the image."""
        if field_name not in self.image_tabs or field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        if not state["original_pixmap"]:
            return
            
        tab, scroll_area, image_label, field_value = self.image_tabs[field_name]

        # Start with original pixmap
        transformed_pixmap = state["original_pixmap"]
        
        # Apply rotation
        if state["rotation"] != 0:
            transform = QTransform()
            transform.rotate(state["rotation"])
            transformed_pixmap = transformed_pixmap.transformed(
                transform, Qt.SmoothTransformation
            )
            
        # Apply zoom
        if state["zoom"] != 1.0:
            new_width = int(transformed_pixmap.width() * state["zoom"])
            new_height = int(transformed_pixmap.height() * state["zoom"])
            transformed_pixmap = transformed_pixmap.scaled(
                new_width, new_height, Qt.KeepAspectRatio, Qt.SmoothTransformation
            )

        # Calculate available space
        available_size = scroll_area.viewport().size()
        available_width = available_size.width() - 20
        available_height = available_size.height() - 20

        # Only auto-fit when not manually zooming and image is larger than viewport
        should_fit = (
            not self.manual_zoom_active and 
            (transformed_pixmap.width() > available_width or 
             transformed_pixmap.height() > available_height)
        )

        if should_fit:
            # Auto-fit mode: scale to fit available space
            fitted_pixmap = transformed_pixmap.scaled(
                available_width,
                available_height,
                Qt.KeepAspectRatio,
                Qt.SmoothTransformation,
            )
            image_label.setPixmap(fitted_pixmap)
            image_label.resize(fitted_pixmap.size())
            
            # Center the fitted image
            x_offset = (available_width - fitted_pixmap.width()) // 2
            y_offset = (available_height - fitted_pixmap.height()) // 2
            image_label.move(max(0, x_offset), max(0, y_offset))
            
            # Reset pan offset when in fit mode
            state["pan_x"] = 0
            state["pan_y"] = 0
            
            #  SET ARROW CURSOR WHEN FITTED 
            scroll_area.viewport().setCursor(Qt.ArrowCursor)
        else:
            # Manual zoom mode: show exact transformed image
            image_label.setPixmap(transformed_pixmap)
            image_label.resize(transformed_pixmap.size())
            
            #  APPLY PAN POSITION - CONVERT TO INTEGERS 
            pan_x_int = int(state["pan_x"])
            pan_y_int = int(state["pan_y"])
            image_label.move(pan_x_int, pan_y_int)
            
            #  ALWAYS SHOW HAND CURSOR IN MANUAL MODE - PANNING ALWAYS AVAILABLE 
            scroll_area.viewport().setCursor(Qt.OpenHandCursor)

        image_label.setText("")

        # Update info label with current state
        self.update_image_info(field_name)

    def wheelEvent(self, event):
        """Handle mouse wheel zoom - zoom to cursor position without any scrolling."""
        field_name = self.get_current_image_field()
        
        # Only handle zoom if we're on an image tab and have a valid image
        if field_name and field_name in self.image_states:
            state = self.image_states[field_name]
            if state["original_pixmap"]:
                # Get the scroll area and image label
                tab, scroll_area, image_label, field_value = self.image_tabs[field_name]
                
                # Get mouse position relative to the scroll area viewport
                mouse_pos = scroll_area.viewport().mapFromGlobal(QCursor.pos())
                
                # Store current state before zooming
                old_pan_x = state["pan_x"]
                old_pan_y = state["pan_y"]
                old_zoom = state["zoom"]
                
                # Calculate new zoom level
                if event.angleDelta().y() > 0:
                    # Zoom in
                    new_zoom = min(state["zoom"] * 1.25, 10.0)
                else:
                    # Zoom out
                    new_zoom = max(state["zoom"] * 0.75, 0.05)
                
                # Calculate the fixed point in viewport coordinates
                fixed_point_viewport_x = mouse_pos.x()
                fixed_point_viewport_y = mouse_pos.y()
                
                # Calculate the fixed point in image coordinates (before zoom)
                fixed_point_image_x = (fixed_point_viewport_x - old_pan_x) / old_zoom
                fixed_point_image_y = (fixed_point_viewport_y - old_pan_y) / old_zoom
                
                # After zoom, we want the same image point to be under the cursor
                new_pan_x = fixed_point_viewport_x - (fixed_point_image_x * new_zoom)
                new_pan_y = fixed_point_viewport_y - (fixed_point_image_y * new_zoom)
                
                # Apply the new zoom and pan - STORE AS INTEGERS
                state["zoom"] = new_zoom
                state["pan_x"] = int(new_pan_x)  #  CONVERT TO INT 
                state["pan_y"] = int(new_pan_y)  #  CONVERT TO INT 
                
                # Activate manual zoom
                self.manual_zoom_active = True
                
                # Apply transformations and update display
                self.apply_image_transformations(field_name)
                
                event.accept()
                return
    
        # Default behavior for other cases
        super().wheelEvent(event)

    def eventFilter(self, obj, event):
        """Handle mouse events for image panning and block wheel events on scroll area."""
        # Check if this event is for one of our image scroll areas or labels
        current_field = None
        scroll_area = None
        image_label = None
        
        for field_name, (tab, sa, img_label, field_value) in self.image_tabs.items():
            if obj == sa.viewport() or obj == img_label:
                current_field = field_name
                scroll_area = sa
                image_label = img_label
                break
        
        if not current_field or not scroll_area:
            return False
        
        event_type = event.type()
        
        #  BLOCK WHEEL EVENTS ON SCROLL AREA - WE HANDLE THEM IN wheelEvent 
        if event_type == QtCore.QEvent.Wheel:
            # Let our wheelEvent method handle this - don't allow scroll area to process it
            self.wheelEvent(event)
            return True  # Block the event from reaching the scroll area
        
        # Use global positions to make dragging stable even if cursor leaves widget
        if event_type == QtCore.QEvent.MouseButtonPress:
            if event.button() == Qt.LeftButton:
                #  ALWAYS ALLOW DRAGGING IN MANUAL ZOOM MODE - EVEN AT MINIMAL ZOOM 
                if not self.manual_zoom_active:
                    return False
                    
                # Start dragging - NO RESTRICTIONS ON ZOOM LEVEL
                self.dragging = True
                self.current_panning_field = current_field
                # store global start position
                self.drag_start_global = event.globalPos()
                # store starting label position
                self.drag_label_start_pos = image_label.pos()
                
                # Change cursor to closed hand
                scroll_area.viewport().setCursor(Qt.ClosedHandCursor)
                event.accept()
                return True
        
        elif event_type == QtCore.QEvent.MouseMove:
            if self.dragging and self.current_panning_field == current_field:
                # Calculate drag distance using global positions
                current_global = event.globalPos()
                delta = current_global - self.drag_start_global
                
                # Calculate new label position
                new_pos = self.drag_label_start_pos + delta
                
                # Apply the new position - USE INTEGER COORDINATES
                image_label.move(new_pos.x(), new_pos.y())
                
                # Store pan offset for reference - AS INTEGERS
                state = self.image_states[current_field]
                state["pan_x"] = int(new_pos.x())  # CONVERT TO INT 
                state["pan_y"] = int(new_pos.y())  # CONVERT TO INT 
                
                event.accept()
                return True
        
        elif event_type == QtCore.QEvent.MouseButtonRelease:
            if event.button() == Qt.LeftButton and self.dragging and self.current_panning_field == current_field:
                # Stop dragging
                self.dragging = False
                self.current_panning_field = None
                self.drag_start_global = None
                self.drag_label_start_pos = None
                # Change cursor back to open hand
                scroll_area.viewport().setCursor(Qt.OpenHandCursor)
                event.accept()
                return True
        
        return False

    def update_image_info(self, field_name):
        """Update the info label with current zoom and rotation state."""
        if field_name not in self.image_states:
            return

        state = self.image_states[field_name]
        tab, scroll_area, image_label, field_value = self.image_tabs[field_name]

        image_path = str(field_value).strip()
        display_name = self.get_display_name(field_name)

        info_text = f"<b>Field:</b> {display_name}<br>"
        info_text += f"<b>Original Name:</b> {field_name}<br>"
        info_text += f"<b>Path:</b> {image_path}<br>"
        info_text += f"<b>Zoom:</b> {state['zoom']:.2f}x<br>"
        info_text += f"<b>Rotation:</b> {state['rotation']}°"

        self.imageInfoLabel.setText(info_text)

    def on_tab_changed(self, index):
        """Handle tab changes to update image info."""
        if index == 0:  # "No Images" tab
            self.imageInfoLabel.setText("No images available for this feature")
            return

        # Get the field name for this tab
        field_name = list(self.image_tabs.keys())[index - 1]  # -1 for "No Images" tab
        field_value = self.image_tabs[field_name][3]

        self.display_image(field_name, field_value)

    def display_image(self, field_name, field_value):
        """Display image and update info label."""
        if field_name not in self.image_tabs:
            return

        tab, scroll_area, image_label, stored_value = self.image_tabs[field_name]

        # Update info label
        self.update_image_info(field_name)

        # Load and display the image
        self.load_and_display_image(field_name)

    def load_and_display_image(self, field_name):
        """Load and display image for the given field."""
        if field_name not in self.image_tabs:
            return

        tab, scroll_area, image_label, field_value = self.image_tabs[field_name]

        try:
            image_str = str(field_value).strip()

            if not image_str or image_str == "NULL":
                image_label.setText("No image path provided")
                return

            pixmap = self.load_image(image_str)

            if pixmap and not pixmap.isNull():
                # Store original pixmap and reset state
                self.image_states[field_name]["original_pixmap"] = pixmap
                
                # Calculate initial zoom to fit the rotated image
                available_size = scroll_area.viewport().size()
                available_width = available_size.width() - 20
                available_height = available_size.height() - 20
                
                # Apply rotation to calculate correct dimensions
                rotated_pixmap = pixmap
                transform = QTransform()
                transform.rotate(90)
                rotated_pixmap = rotated_pixmap.transformed(transform, Qt.SmoothTransformation)
                
                # Calculate the zoom level that fits the rotated image
                width_ratio = available_width / rotated_pixmap.width() if rotated_pixmap.width() > 0 else 1.0
                height_ratio = available_height / rotated_pixmap.height() if rotated_pixmap.height() > 0 else 1.0
                actual_fit_zoom = min(width_ratio, height_ratio)
                
                # Set the actual initial zoom level
                self.image_states[field_name]["zoom"] = actual_fit_zoom
                self.image_states[field_name]["rotation"] = 90
                self.image_states[field_name]["pan_x"] = 0  #  RESET PAN OFFSET
                self.image_states[field_name]["pan_y"] = 0  #  RESET PAN OFFSET 
                
                # Start in manual zoom mode to prevent jumps
                self.manual_zoom_active = True

                # Apply transformations
                self.apply_image_transformations(field_name)

            else:
                image_label.setText(
                    f"Could not load image\n{os.path.basename(image_str)}"
                )

        except Exception as e:
            image_label.setText(f"Error loading image\n{str(e)}")

    def resize_image_to_fit(self, image_label, scroll_area):
        """Resize image to fit the current scroll area size."""
        field_name = self.get_current_image_field()
        if field_name and field_name in self.image_states:
            state = self.image_states[field_name]
            if state["original_pixmap"]:
                self.apply_image_transformations(field_name)

    def load_image(self, image_path):
        """Load image from local path."""
        image_str = str(image_path).strip()

        # Handle file:// URLs
        if image_str.startswith("file://"):
            image_str = image_str[7:]

        # Skip if path is NULL or empty
        if not image_str or image_str == "NULL":
            return None

        # Try as absolute path
        if os.path.isabs(image_str) and os.path.exists(image_str):
            return QPixmap(image_str)

        # Try relative to project file
        from qgis.core import QgsProject # type: ignore

        project_path = QgsProject.instance().fileName()
        if project_path:
            project_dir = os.path.dirname(project_path)
            relative_path = os.path.join(project_dir, image_str)
            if os.path.exists(relative_path):
                return QPixmap(relative_path)

        # Try relative to plugin directory
        plugin_dir = os.path.dirname(__file__)
        plugin_relative_path = os.path.join(plugin_dir, image_str)
        if os.path.exists(plugin_relative_path):
            return QPixmap(plugin_relative_path)

        # Try relative to QGIS project home directory
        home_path = os.path.expanduser("~")
        home_relative_path = os.path.join(home_path, image_str)
        if os.path.exists(home_relative_path):
            return QPixmap(home_relative_path)

        # Try current working directory
        cwd_path = os.path.join(os.getcwd(), image_str)
        if os.path.exists(cwd_path):
            return QPixmap(cwd_path)

        return None

    def resizeEvent(self, event):
        """Handle resize events to update images and table."""
        super().resizeEvent(event)

        # Update table column widths
        table_width = self.attributeTable.width()
        self.attributeTable.setColumnWidth(0, int(table_width * 0.4))  # 40% for field names
        self.attributeTable.setColumnWidth(1, int(table_width * 0.6))  # 60% for values

        # Only update images if not in manual zoom mode
        if not self.manual_zoom_active:
            for field_name in self.image_tabs:
                tab, scroll_area, image_label, field_value = self.image_tabs[field_name]
                self.resize_image_to_fit(image_label, scroll_area)

    def open_image_in_system_viewer(self, image_path):
        """Open image in system's default image viewer."""
        try:
            image_str = str(image_path).strip()
            if not image_str or image_str == "NULL":
                return
            
            # Handle file:// URLs
            if image_str.startswith('file://'):
                image_str = image_str[7:]
            
            # Try to find the absolute path
            absolute_path = self.find_absolute_image_path(image_str)
            
            if absolute_path and os.path.exists(absolute_path):
                # Open image with system default viewer
                if os.name == 'nt':  # Windows
                    os.startfile(absolute_path)
            else:
                QtWidgets.QMessageBox.warning(self, "Image Not Found", 
                                            f"Could not find image file:\n{image_str}")
                
        except Exception as e:
            QtWidgets.QMessageBox.warning(self, "Error", 
                                        f"Could not open image:\n{str(e)}")

    def find_absolute_image_path(self, image_path):
        """Find the absolute path of an image file."""
        image_str = str(image_path).strip()
        
        # Try as absolute path
        if os.path.isabs(image_str) and os.path.exists(image_str):
            return image_str
        
        # Try relative to project file
        from qgis.core import QgsProject # type: ignore
        project_path = QgsProject.instance().fileName()
        if project_path:
            project_dir = os.path.dirname(project_path)
            relative_path = os.path.join(project_dir, image_str)
            if os.path.exists(relative_path):
                return relative_path
        
        # Try relative to plugin directory
        plugin_dir = os.path.dirname(__file__)
        plugin_relative_path = os.path.join(plugin_dir, image_str)
        if os.path.exists(plugin_relative_path):
            return plugin_relative_path
        
        # Try relative to QGIS project home directory
        home_path = os.path.expanduser("~")
        home_relative_path = os.path.join(home_path, image_str)
        if os.path.exists(home_relative_path):
            return home_relative_path
        
        # Try current working directory
        cwd_path = os.path.join(os.getcwd(), image_str)
        if os.path.exists(cwd_path):
            return cwd_path
        
        return None