# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MerginToolDialog
                                 A QGIS plugin
 merge design sessions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2025 by M.desing
        email                : info@mdesignsolutions.be
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from qgis.PyQt import uic # type: ignore
from qgis.PyQt.QtWidgets import QDialog, QFileDialog, QMessageBox, QListWidgetItem
from qgis.PyQt.QtCore import QSettings
from .merge_logic import InstanceMerger

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'mergin_tool_dialog_base.ui'))


class MergeInstancesDialog(QDialog, FORM_CLASS):
    
    def __init__(self, parent=None):
        """Constructor."""
        super(MergeInstancesDialog, self).__init__(parent)
        self.setupUi(self)
        
        # Initialize instance merger
        self.merger = InstanceMerger()
        
        # Connect signals
        self.btnAddInstance.clicked.connect(self.add_instance)
        self.btnRemoveInstance.clicked.connect(self.remove_instance)
        self.btnClearAll.clicked.connect(self.clear_instances)
        self.btnBrowseFolder.clicked.connect(self.browse_output_folder)
        self.btnMerge.clicked.connect(self.merge_instances)
        self.btnClose.clicked.connect(self.close)
        
        # Load settings
        self.load_settings()
        
        # Connect merger signals
        self.merger.progress_updated.connect(self.update_progress)
        self.merger.log_message.connect(self.log_message)
        self.merger.merge_finished.connect(self.merge_finished)
        
    def add_instance(self):
        """Add QGIS project files to the list."""
        files, _ = QFileDialog.getOpenFileNames(
            self, 
            "Select QGIS Project Files",
            "",
            "QGIS Project Files (*.qgz *.qgs);;All Files (*)"
        )
        
        for file in files:
            if self.is_valid_project_file(file):
                item = QListWidgetItem(file)
                self.lstInstances.addItem(item)
                self.log_message(f"Added project: {os.path.basename(file)}")
            elif file:
                QMessageBox.warning(self, "Invalid File", 
                                  "Selected file is not a valid QGIS project file.")
    
    def is_valid_project_file(self, file_path):
        """Check if file is a valid QGIS project file."""
        return os.path.isfile(file_path) and file_path.lower().endswith(('.qgs', '.qgz'))
    
    def remove_instance(self):
        """Remove selected instance from list."""
        current_row = self.lstInstances.currentRow()
        if current_row >= 0:
            item = self.lstInstances.takeItem(current_row)
            self.log_message(f"Removed project: {os.path.basename(item.text())}")
    
    def clear_instances(self):
        """Clear all instances from list."""
        self.lstInstances.clear()
        self.log_message("Cleared all projects")
    
    def browse_output_folder(self):
        """Browse for output folder."""
        folder = QFileDialog.getExistingDirectory(
            self,
            "Select Output Folder",
            self.txtOutputFolder.text() or "",
            QFileDialog.ShowDirsOnly
        )
        
        if folder:
            self.txtOutputFolder.setText(folder)
    
    def merge_instances(self):
        """Start the merging process."""
        # Validate inputs
        if self.lstInstances.count() < 2:
            QMessageBox.warning(self, "Insufficient Projects", 
                              "Please add at least 2 project files to merge.")
            return
            
        if not self.txtOutputFolder.text():
            QMessageBox.warning(self, "Output Required", 
                              "Please select an output folder.")
            return
        
        if not self.txtOutputName.text().strip():
            QMessageBox.warning(self, "Project Name Required", 
                              "Please enter an output project name.")
            return
        
        # Check if project folder already exists
        project_folder = os.path.join(self.txtOutputFolder.text(), self.txtOutputName.text().strip())
        if os.path.exists(project_folder):
            reply = QMessageBox.question(
                self, 
                "Folder Exists", 
                f"The project folder '{self.txtOutputName.text().strip()}' already exists. Do you want to overwrite it?",
                QMessageBox.Yes | QMessageBox.No,
                QMessageBox.No
            )
            if reply == QMessageBox.No:
                return
            
        # Get project file paths
        project_paths = []
        for i in range(self.lstInstances.count()):
            project_paths.append(self.lstInstances.item(i).text())
        
        # Get instance folders (parent directories of project files)
        instance_paths = [os.path.dirname(path) for path in project_paths]
        
        # Set merger parameters
        self.merger.set_parameters(
            instance_paths=instance_paths,
            output_folder=self.txtOutputFolder.text(),
            output_name=self.txtOutputName.text().strip(),
            merge_DCIM=self.chkMergeDCIM.isChecked(),
            preserve_styles=self.chkPreserveStyles.isChecked(),
            create_backup=self.chkCreateBackup.isChecked()
        )
        
        # Disable UI during merge
        self.set_ui_enabled(False)
        self.progressBar.setValue(0)
        self.txtLog.clear()
        
        # Start merge
        self.merger.start_merge()
    
    def update_progress(self, value, message):
        """Update progress bar and log."""
        self.progressBar.setValue(value)
        if message:
            self.log_message(message)
    
    def log_message(self, message):
        """Add message to log."""
        self.txtLog.append(f"• {message}")
        # Auto-scroll to bottom
        self.txtLog.verticalScrollBar().setValue(
            self.txtLog.verticalScrollBar().maximum()
        )
    
    def merge_finished(self, success, message):
        """Handle merge completion."""
        self.set_ui_enabled(True)
        
        if success:
            QMessageBox.information(self, "Merge Complete", message)
            self.progressBar.setValue(100)
        else:
            QMessageBox.critical(self, "Merge Failed", message)
            self.progressBar.setValue(0)
    
    def set_ui_enabled(self, enabled):
        """Enable/disable UI elements during merge."""
        self.btnAddInstance.setEnabled(enabled)
        self.btnRemoveInstance.setEnabled(enabled)
        self.btnClearAll.setEnabled(enabled)
        self.btnBrowseFolder.setEnabled(enabled)
        self.btnMerge.setEnabled(enabled)
        self.txtOutputName.setEnabled(enabled)
        self.txtOutputFolder.setEnabled(enabled)
        self.chkMergeDCIM.setEnabled(enabled)
        self.chkPreserveStyles.setEnabled(enabled)
        self.chkCreateBackup.setEnabled(enabled)
    
    def load_settings(self):
        """Load previous settings."""
        settings = QSettings()
        last_folder = settings.value("merge_instances/last_folder", "")
        self.txtOutputFolder.setText(last_folder)
    
    def save_settings(self):
        """Save current settings."""
        settings = QSettings()
        settings.setValue("merge_instances/last_folder", self.txtOutputFolder.text())
    
    def closeEvent(self, event):
        """Handle dialog close."""
        self.save_settings()
        super().closeEvent(event)